language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
before_script:
  - composer self-update
  - composer install --no-interaction
  - tests/runinstall 
script:
  - vendor/bin/phpunit
  - cat suitecrm.log
services:
  - mysql
branches:
  only:
    - develop
