language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
matrix:
  allow_failures:
    - php: 7.0    # This is not a php7-ready project - this should be disabled alltogether
    - php: hhvm   # ZIP Error(11): Status(0): Arhive(cache/zipTest.zip): Directory(cache)
before_script:
  - composer self-update
  - composer install --no-interaction
  - \[ -f "config_si.php" \] || curl -L https://gist.githubusercontent.com/JimMackin/c3db403bae59c2c9a27c/raw/config_si.php > config_si.php
  - php tests/testinstall.php
script:
  - cd tests
  - ../vendor/bin/phpunit
  - cat ../suitecrm.log
services:
  - mysql
branches:
  only:
    - master
    - hotfix
    - develop
    - travisFix
