version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: suitecrm-mysql
    environment:
      MYSQL_ROOT_PASSWORD: suitecrm_root
      MYSQL_DATABASE: suitecrm
      MYSQL_USER: suitecrm
      MYSQL_PASSWORD: suitecrm_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - suitecrm-network

  # PHP Application with Mobile Real Estate
  suitecrm:
    build:
      context: .
      dockerfile: Dockerfile.suitecrm
    container_name: suitecrm-mobile
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html
      - ./cobol-integration:/var/www/cobol-integration
      - suitecrm_uploads:/var/www/html/upload
      - suitecrm_cache:/var/www/html/cache
    environment:
      DATABASE_HOST: mysql
      DATABASE_NAME: suitecrm
      DATABASE_USER: suitecrm
      DATABASE_PASSWORD: suitecrm_pass
      SITE_URL: http://localhost:8082
      COBOL_HOST: cobol-gateway
      COBOL_PORT: 8080
      COBOL_WEBSOCKET: ws://cobol-gateway:8081
    depends_on:
      - mysql
      - cobol-gateway
    networks:
      - suitecrm-network

  # COBOL Gateway Service
  cobol-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: cobol-gateway
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8090:8090"
    volumes:
      - ./cobol/programs:/app/programs
      - ./cobol/data:/app/data
      - ./cobol/gateway:/app
    environment:
      NODE_ENV: production
      COBOL_PORT: 8080
      COBOL_WS_PORT: 8081
      USE_MOCK_COBOL: "true"
    networks:
      - suitecrm-network

  # COBOL Runtime Container
  cobol-runtime:
    build:
      context: .
      dockerfile: Dockerfile.cobol
    container_name: cobol-runtime
    volumes:
      - ./cobol/programs:/cobol/programs
      - ./cobol/data:/cobol/data
      - cobol_workdir:/cobol/work
    environment:
      COBOL_ENV: production
    networks:
      - suitecrm-network

  # Redis for Queue Management
  redis:
    image: redis:7-alpine
    container_name: suitecrm-redis
    ports:
      - "6379:6379"
    networks:
      - suitecrm-network

volumes:
  mysql_data:
  suitecrm_uploads:
  suitecrm_cache:
  cobol_workdir:

networks:
  suitecrm-network:
    driver: bridge