<?php
/**
 * This file is part of SinergiaCRM.
 * SinergiaCRM is a work developed by SinergiaTIC Association, based on SuiteCRM.
 * Copyright (C) 2013 - 2023 SinergiaTIC Association
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SinergiaTIC Association at email address info@sinergiacrm.org.
 */
// Prevents directly accessing this file from a web browser
if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

include_once "modules/stic_AWF_Forms/actions/coreActions.php";

/**
 * RelateRecordsAction
 *
 * Action that establishes a relationship between two Data Blocks in the Database.
 */
class RelateRecordsAction extends HookBeanActionDefinition {
    public function __construct() {
        $this->isActive = true;
        $this->isUserSelectable = false; // Users cannot select this action manually
        $this->isAutomatic = true;       // The action is automatically generated by the system
        $this->category = 'data';
        $this->baseLabel = 'LBL_RELATE_RECORDS_ACTION';
    }

    /**
     * getCustomParameters()
     * Definition of the ADDITIONAL parameters needed for the action
     * The parameter of the main Data Block is requested by the parent class.
     */
    protected function getCustomParameters(): array
    {
        // Target of the relationship (required): Can be a Data Block or a Record ID
        $paramTarget = new ActionParameterDefinition();
        $paramTarget->name = 'target_object';
        $paramTarget->text = $this->translate('TARGET_OBJECT_TEXT');
        $paramTarget->description = $this->translate('TARGET_OBJECT_DESC');
        $paramTarget->type = ActionParameterType::OPTION_SELECTOR; 
        $paramTarget->required = true;

        // The Target Data Block
        $optTargetBlock = new ActionSelectorOptionDefinition();
        $optTargetBlock->name = 'datablock';
        $optTargetBlock->text = $this->translate('OPTION_BLOCK_TEXT');
        $optTargetBlock->resolvedType = ActionParameterType::DATA_BLOCK;

        // The ID of the Target record
        $optValue = new ActionSelectorOptionDefinition();
        $optValue->name = 'value';
        $optValue->text = $this->translate('OPTION_VALUE_TEXT');
        $optValue->resolvedType = ActionParameterType::VALUE;
        $optValue->resolvedDataType = ActionDataType::TEXT;

        // Target options
        $paramTarget->selectorOptions = [$optTargetBlock, $optValue];
        $paramTarget->defaultValue = 'datablock';


        // The name of the relationship (which points to the target Data Block)
        $paramRelName = new ActionParameterDefinition();
        $paramRelName->name = 'relationship_name';
        $paramRelName->text = $this->translate('RELATIONSHIP_TEXT');
        $paramRelName->description = $this->translate('RELATIONSHIP_DESC');
        $paramRelName->type = ActionParameterType::VALUE; 
        $paramRelName->dataType = ActionDataType::TEXT; 
        $paramRelName->required = true;

        // The id_name of the FK field (for 1-N relationships: virtual or canonical)
        $paramIdName = new ActionParameterDefinition();
        $paramIdName->name = 'relation_id_name';
        $paramIdName->text = $this->translate('RELATION_ID_NAME_TEXT');
        $paramIdName->type = ActionParameterType::VALUE;
        $paramIdName->dataType = ActionDataType::TEXT;
        $paramIdName->required = false;

        return [$paramTarget, $paramRelName, $paramIdName];
    }


    public function executeWithBean(ExecutionContext $context, FormAction $actionConfig, SugarBean $bean, DataBlockResolved $block): ActionResult
    {
        // Mark the bean as being processed within AWF context to enable AWF-specific behavior
        if (property_exists($bean, 'fromAWF')) {
            $bean->fromAWF = true;
        }

        // Get additional parameters (ParameterResolver ensures they are not null because they are required)

        /** @var OptionSelectorResolved $targetObjectSelector */
        $targetObjectSelector = $actionConfig->getResolvedParameter('target_object');
        $linkName = $actionConfig->getResolvedParameter('relationship_name');

        // Support both formats: SuiteCRM relationship name and legacy compound key (Module__linkName)
        if (strpos($linkName, '__') !== false) {
            $parts = explode('__', $linkName, 2);
            $relName = $parts[0];
            $linkName = $parts[1];
        }

        // If the value is a relationship name (not a link field name), resolve it
        // to the actual link field by scanning vardefs. This covers cases where the
        // relationship_name parameter was populated with the relationship name
        // instead of the link name (e.g., cached module info without link_name).
        if (!empty($linkName) && !isset($bean->field_defs[$linkName])) {
            foreach ($bean->field_defs as $fieldName => $def) {
                if (isset($def['type']) && $def['type'] === 'link'
                    && isset($def['relationship']) && $def['relationship'] === $linkName) {
                    $GLOBALS['log']->debug("RelateRecordsAction: Resolved relationship name '{$linkName}' to link field '{$fieldName}'.");
                    $linkName = $fieldName;
                    break;
                }
            }
        }

        // Validation of selector parameter
        if (!$targetObjectSelector || !($targetObjectSelector instanceof OptionSelectorResolved)) {
            return new ActionResult(ResultStatus::ERROR, $actionConfig, "Invalid target_object parameter type.");
        }

        // Validation of relationship name
        if (empty($linkName)) {
            return new ActionResult(ResultStatus::ERROR, $actionConfig, "Relationship name is not specified.");
        }        

        // Getting the ID of the destination Bean
        $targetBeanId = null;
        // Option selected in the selector: can be a Data Block or a direct ID
        if ($targetObjectSelector->selectedOptionName == 'datablock') {
            /** @var DataBlockResolved $targetDataBlock */
            $targetDataBlock = $targetObjectSelector->resolvedValue;
            if (!$targetDataBlock || !($targetDataBlock instanceof DataBlockResolved)) {
                return new ActionResult(ResultStatus::ERROR, $actionConfig, "Invalid value in target_object parameter as datablock: is not a valid DataBlockResolved.");
            }
            $targetBeanRef = $targetDataBlock->dataBlock->getBeanReference();
            if ($targetBeanRef === null || empty($targetBeanRef->beanId)) {
                return new ActionResult(ResultStatus::ERROR, $actionConfig, "Destination data block '{$targetDataBlock->dataBlock->name}' has no ID. Check Action Order.");
            }
            $targetBeanId = $targetBeanRef->beanId;
        } else if ($targetObjectSelector->selectedOptionName == 'value') {
            /** @var string $targetValue */
            $targetValue = $targetObjectSelector->resolvedValue;
            if (!is_string($targetValue) || empty($targetValue)) {
                return new ActionResult(ResultStatus::ERROR, $actionConfig, "Invalid value in target_object parameter as value: must be a non-empty string.");
            }
            $targetBeanId = $targetValue;
        } else {
            return new ActionResult(ResultStatus::ERROR, $actionConfig, "Invalid option selected in target_object parameter.");
        }
        
        if (empty($targetBeanId)) {
            return new ActionResult(ResultStatus::ERROR, $actionConfig, "Relationship '{$linkName}' failed: No target ID found.");
        }

        // Determine whether this is a FK-based (1-N) or link-based (N-M) relationship
        $relationIdName = $actionConfig->getResolvedParameter('relation_id_name', '');

        if (!empty($relationIdName)) {
            // 1-N relationship: inject FK directly and re-save the bean
            $GLOBALS['log']->debug("RelateRecordsAction: Using FK injection for '{$linkName}' — setting '{$relationIdName}' = '{$targetBeanId}' on bean '{$bean->id}'.");

            $bean->{$relationIdName} = $targetBeanId;
            stic_AWF_FormsUtils::populateRelateDisplayField($bean, $relationIdName, $targetBeanId);

            if (property_exists($bean, 'fromAWF')) {
                $bean->fromAWF = true;
            }
            $bean->save(false);

            // Recalculate name (if necessary)
            stic_AWF_FormsUtils::recalculateNameIfNeeded($bean, $block, $context);

            $actionResult = new ActionResult(ResultStatus::OK, $actionConfig, "Linked via FK '{$relationIdName}' to ID {$targetBeanId}");
            $dataToLog = [
                ['key' => 'relationship_name', 'label' => $this->translate('RELATIONSHIP_TEXT'), 'value' => $linkName],
                ['key' => 'target_object', 'label' => $this->translate('TARGET_OBJECT_TEXT'), 'value' => $targetBeanId],
                ['key' => 'fk_field', 'label' => $this->translate('RELATION_ID_NAME_TEXT'), 'value' => $relationIdName],
            ];
            $actionResult->registerActionMetadata($bean, $dataToLog);

            return $actionResult;
        }

        // N-M relationship (or canonical 1-N without explicit id_name): use link-based relationship
        if (!$bean->load_relationship($linkName)) {
            return new ActionResult(ResultStatus::SKIPPED, $actionConfig, "Could not load relationship '{$linkName}' in module '{$bean->module_name}'. Check vardefs link name.");
        }
        if (!($bean->$linkName instanceof Link2)) {
            $type = gettype($bean->$linkName);
            return new ActionResult(ResultStatus::ERROR, $actionConfig, "Error: '{$linkName}' acts as a '{$type}', not a Relationship Link. Please check if you are using the Field Name instead of the Link Name in the configuration.");
        }

        try {
            $bean->$linkName->add($targetBeanId);
        } catch (\Exception $e) {
            return new ActionResult(ResultStatus::ERROR, $actionConfig, "Error linking records: " . $e->getMessage());
        }

        // Recalculate name (if necessary)
        stic_AWF_FormsUtils::recalculateNameIfNeeded($bean, $block, $context);

        $actionResult = new ActionResult(ResultStatus::OK, $actionConfig, "Linked via '{$linkName}' to ID {$targetBeanId}");
        $dataToLog = [
            ['key' => 'relationship_name', 'label' => $this->translate('RELATIONSHIP_TEXT'), 'value' => $linkName],
            ['key' => 'target_object', 'label' => $this->translate('TARGET_OBJECT_TEXT'), 'value' => $targetBeanId],
        ];
        $actionResult->registerActionMetadata($bean, $dataToLog);

        return $actionResult;
    }

}