<?php
/**
 * This file is part of SinergiaCRM.
 * SinergiaCRM is a work developed by SinergiaTIC Association, based on SuiteCRM.
 * Copyright (C) 2013 - 2023 SinergiaTIC Association
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SinergiaTIC Association at email address info@sinergiacrm.org.
 */
// Prevents directly accessing this file from a web browser
if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

include_once "modules/stic_AWF_Forms/actions/coreActions.php";

/**
 * RelateRecordsAction
 *
 * Action that establishes a relationship between two Data Blocks in the Database.
 */
class RelateRecordsAction extends HookBeanActionDefinition {
    public function __construct() {
        $this->isActive = true;
        $this->isUserSelectable = false; // Users cannot select this action manually
        $this->isAutomatic = true;       // The action is automatically generated by the system
        $this->category = 'data';
        $this->baseLabel = 'LBL_RELATE_RECORDS_ACTION';
    }

    /**
     * getCustomParameters()
     * Definition of the ADDITIONAL parameters needed for the action
     * The parameter of the main Data Block is requested by the parent class.
     */
    protected function getCustomParameters(): array
    {
        // Target of the relationship (required): Can be a Data Block or a Record ID
        $paramTarget = new ActionParameterDefinition();
        $paramTarget->name = 'target_object';
        $paramTarget->text = $this->translate('TARGET_OBJECT_TEXT');
        $paramTarget->description = $this->translate('TARGET_OBJECT_DESC');
        $paramTarget->type = ActionParameterType::OPTION_SELECTOR; 
        $paramTarget->required = true;

        // The Target Data Block
        $optTargetBlock = new ActionSelectorOptionDefinition();
        $optTargetBlock->name = 'datablock';
        $optTargetBlock->text = $this->translate('OPTION_BLOCK_TEXT');
        $optTargetBlock->resolvedType = ActionParameterType::DATA_BLOCK;

        // The ID of the Target record
        $optValue = new ActionSelectorOptionDefinition();
        $optValue->name = 'value';
        $optValue->text = $this->translate('OPTION_VALUE_TEXT');
        $optValue->resolvedType = ActionParameterType::VALUE;
        $optValue->resolvedDataType = ActionDataType::TEXT;

        // Target options
        $paramTarget->selectorOptions = [$optTargetBlock, $optValue];
        $paramTarget->defaultValue = 'datablock';


        // The name of the relationship (which points to the target Data Block)
        $paramRelName = new ActionParameterDefinition();
        $paramRelName->name = 'relationship_name';
        $paramRelName->text = $this->translate('RELATIONSHIP_TEXT');
        $paramRelName->description = $this->translate('RELATIONSHIP_DESC');
        $paramRelName->type = ActionParameterType::VALUE; 
        $paramRelName->dataType = ActionDataType::TEXT; 
        $paramRelName->required = true;

        return [$paramTarget, $paramRelName];
    }


    public function executeWithBean(ExecutionContext $context, FormAction $actionConfig, SugarBean $bean, DataBlockResolved $block): ActionResult
    {
        // Get additional parameters (ParameterResolver ensures they are not null because they are required)

        /** @var OptionSelectorResolved $targetObjectSelector */
        $targetObjectSelector = $actionConfig->getResolvedParameter('target_object');
        $linkName = $actionConfig->getResolvedParameter('relationship_name');

        // Validation of selector parameter
        if (!$targetObjectSelector || !($targetObjectSelector instanceof OptionSelectorResolved)) {
            return new ActionResult(ResultStatus::ERROR, $actionConfig, "Invalid target_object parameter type.");
        }

        // Validation of relationship name
        if (empty($linkName)) {
            return new ActionResult(ResultStatus::ERROR, $actionConfig, "Relationship name is not specified.");
        }        

        // Getting the ID of the destination Bean
        $targetBeanId = null;
        // Option selected in the selector: can be a Data Block or a direct ID
        if ($targetObjectSelector->selectedOptionName == 'datablock') {
            /** @var DataBlockResolved $targetDataBlock */
            $targetDataBlock = $targetObjectSelector->resolvedValue;
            if (!$targetDataBlock || !($targetDataBlock instanceof DataBlockResolved)) {
                return new ActionResult(ResultStatus::ERROR, $actionConfig, "Invalid value in target_object parameter as datablock: is not a valid DataBlockResolved.");
            }
            $targetBeanRef = $targetDataBlock->dataBlock->getBeanReference();
            if ($targetBeanRef === null || empty($targetBeanRef->beanId)) {
                return new ActionResult(ResultStatus::ERROR, $actionConfig, "Destination data block '{$targetDataBlock->dataBlock->name}' has no ID. Check Action Order.");
            }
            $targetBeanId = $targetBeanRef->beanId;
        } else if ($targetObjectSelector->selectedOptionName == 'value') {
            /** @var string $targetValue */
            $targetValue = $targetObjectSelector->resolvedValue;
            if (!is_string($targetValue) || empty($targetValue)) {
                return new ActionResult(ResultStatus::ERROR, $actionConfig, "Invalid value in target_object parameter as value: must be a non-empty string.");
            }
            $targetBeanId = $targetValue;
        } else {
            return new ActionResult(ResultStatus::ERROR, $actionConfig, "Invalid option selected in target_object parameter.");
        }
        
        if (empty($targetBeanId)) {
            return new ActionResult(ResultStatus::ERROR, $actionConfig, "Relationship '{$linkName}' failed: No target ID found.");
        }

        // Load the relationship in source Bean
        if (!$bean->load_relationship($linkName)) {
            return new ActionResult(ResultStatus::SKIPPED, $actionConfig, "Could not load relationship '{$linkName}' in module '{$bean->module_name}'. Check vardefs link name.");
        }
        // Verify that it is a Link2
        if (!($bean->$linkName instanceof Link2)) {
            $type = gettype($bean->$linkName);
            return new ActionResult(ResultStatus::ERROR, $actionConfig, "Error: '{$linkName}' acts as a '{$type}', not a Relationship Link. Please check if you are using the Field Name instead of the Link Name in the configuration.");
        }

        // Establish the relationship
        // The add() method manages internally whether it is 1:M (foreign keys) or M:M (intermediate tables).
        try {
            $bean->$linkName->add($targetBeanId);
        } catch (\Exception $e) {
            return new ActionResult(ResultStatus::ERROR, $actionConfig, "Error linking records: " . $e->getMessage());
        }

        // Recalculate name (if necessary)
        $nameFieldInBlock = $block->getFieldValue('name');
        $nameIsUserDefined = $nameFieldInBlock && !empty($nameFieldInBlock->value);
        $beanWasCreatedHere = $this->wasBeanCreatedInThisContext($bean->id, $context);

        // The name has not been explicitly indicated, the bean has been created and has a name (calculated)
        if (!$nameIsUserDefined && $beanWasCreatedHere) {
            // Retrieve the bean to have updated data
            $bean->retrieve($bean->id);
            // Reset the name
            $bean->name = '';
            // Save again so that the name is recalculated
            $bean->save();
        }

        // Result notification
        $actionResult = new ActionResult(ResultStatus::OK, $actionConfig, "Linked via '{$linkName}' to ID {$targetBeanId}");
        $dataToLog = [
            ['key' => 'relationship_name', 'label' => $this->translate('RELATIONSHIP_TEXT'), 'value' => $linkName],
            ['key' => 'target_object', 'label' => $this->translate('TARGET_OBJECT_TEXT'), 'value' => $targetBeanId],
        ];
        $actionResult->registerActionMetadata($bean, $dataToLog);

        return $actionResult;
    }

    private function wasBeanCreatedInThisContext(string $beanId, ExecutionContext $context): bool 
    {
        foreach ($context->actionResults as $result) {
            foreach ($result->modifiedBeans as $modBean) {
                if ($modBean->beanId === $beanId && $modBean->modificationType === BeanModificationType::CREATED) {
                    return true;
                }
            }
        }
        return false;
    }
}