<?php
/**
 * This file is part of SinergiaCRM.
 * SinergiaCRM is a work developed by SinergiaTIC Association, based on SuiteCRM.
 * Copyright (C) 2013 - 2023 SinergiaTIC Association
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SinergiaTIC Association at email address info@sinergiacrm.org.
 */
// Prevents directly accessing this file from a web browser
if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

include_once "modules/stic_AWF_Forms/actions/coreActions.php";
include_once "modules/stic_AWF_Forms/Utils.php";

/**
 * SaveRecordAction
 *
 * Action that manages saving a Data Block to the Database.
 */
class SaveRecordAction extends HookDataBlockActionDefinition {
    public function __construct() {
        $this->isActive = true;
        $this->isUserSelectable = false; // Users cannot select this action manually
        $this->isAutomatic = true;       // The action is automatically generated by the system
        $this->category = 'data';
        $this->baseLabel = 'LBL_SAVE_RECORD_ACTION';
    }

    protected function getCustomParameters(): array {
        $paramConfigs = new ActionParameterDefinition();
        $paramConfigs->name = 'relation_configs';
        $paramConfigs->text = $this->translate('RELATION_CONFIGS_TEXT');
        $paramConfigs->type = ActionParameterType::VALUE;
        $paramConfigs->dataType = ActionDataType::TEXT;
        $paramConfigs->required = false;
        return [$paramConfigs];
    }

    /**
     * Executes the action, receiving the resolved and validated main data block.
     *
     * @param ExecutionContext $context The global context.
     * @param FormAction $actionConfig The action configuration.
     * @param DataBlockResolved $block The main data block, ready to be used.
     * @return ActionResult
     */
    public function executeWithBlock(ExecutionContext $context, FormAction $actionConfig, DataBlockResolved $block): ActionResult
    {
        global $db, $beanList;

        $module = $block->dataBlock->module;
        if (!isset($beanList[$module])) {
            return new ActionResult(ResultStatus::ERROR, $actionConfig, "The configured module '{$module}' is not available on the system.");
        }

        $bean = null;
        $onDuplicateAction = null;
        $modifications = [];

        // Duplicate detection logic
        $duplicateRules = $block->dataBlock->duplicate_detections ?? [];
        foreach ($duplicateRules as $rule) {
            $scalarFields = [];
            $emailValues = [];
            $skipRule = false;
            $candidateIds = null;

            $foundBean = null;
            $tempBean = BeanFactory::newBean($module);
            if (!$tempBean) {
                return new ActionResult(ResultStatus::ERROR, $actionConfig, "Failed to create a new instance of the module '{$module}'.");
            }

            // Build the search fields for this rule
            foreach ($rule->fields as $fieldName) {
                $fieldValue = $block->getFieldValue($fieldName)?->value;

                // If a field in the duplicate rule is empty, do not apply the rule
                // (Two persons cannot be the same if both have an empty email field)
                if ($fieldValue === null || $fieldValue === '') {
                    $skipRule = true;
                    break; // Move to the next rule
                }
                if (stic_AWF_FormsUtils::isEmailField($tempBean->field_defs[$fieldName] ?? null, $fieldName)) {
                    $emailValues[] = $fieldValue;
                } else {
                    $scalarFields[$fieldName] = $fieldValue;
                }
            }
            if ($skipRule) {
                continue; // Move to the next rule
            }

            // Email duplicate check
            if (!empty($emailValues)) {
                // Rule includes emails: JOIN with email table
                foreach ($emailValues as $email) {
                    // Query to find IDs that have THIS specific email
                    $sql = "SELECT DISTINCT ebr.bean_id 
                            FROM email_addr_bean_rel ebr
                            INNER JOIN email_addresses ea ON ebr.email_address_id = ea.id
                            WHERE ebr.bean_module = '{$module}'
                                AND ebr.deleted = 0 
                                AND ea.deleted = 0
                                AND ea.email_address = '" . $db->quote($email) . "'";
            
                    $result = $db->query($sql);
                    $idsFoundForThisEmail = [];
                    while ($row = $db->fetchByAssoc($result)) {
                        $idsFoundForThisEmail[] = $row['bean_id'];
                    }
                    if ($candidateIds === null) {
                        // Is the first email checked, the candidates are the ones we found
                        $candidateIds = $idsFoundForThisEmail;
                    } else {
                        // Already had candidates from a previous email.
                        // Do the INTERSECTION: Only use those that have THE PREVIOUS and THE CURRENT.
                        $candidateIds = array_intersect($candidateIds, $idsFoundForThisEmail);
                    }
                    // If no candidates: break loop
                    if (empty($candidateIds)) {
                        break;
                    }
                }
                // If after looking at the emails we have no candidates, this rule has failed
                if (empty($candidateIds)) {
                   continue;
                }
            }

            // Scalar duplicate check
            $foundBean = null;

            if ($candidateIds !== null) {
                // Found candidates via Email.
                // Verify if these candidates satisfy the rest of the scalar fields.
                foreach ($candidateIds as $id) {
                    $beanToCheck = BeanFactory::getBean($module, $id);
                    if ($beanToCheck) {
                        $match = true;
                        foreach ($scalarFields as $sField => $sValue) {
                            if (($beanToCheck->$sField ?? null) != $sValue) {
                                $match = false;
                                break;
                            }
                        }
                        if ($match) {
                            $foundBean = $beanToCheck;
                            break; // Full match found
                        }
                    }
                }
            } else {
                // The rule did NOT have emails. Only scalar fields.
                if (!empty($scalarFields)) {
                    $tempBean = BeanFactory::newBean($module);
                    $foundBean = $tempBean->retrieve_by_string_fields($scalarFields);
                }
            }

            if ($foundBean !== null) {
                if (!empty($foundBean->id)) {
                    $foundBean->retrieve($foundBean->id);
                }
                $bean = $foundBean; // Duplicate found
                $onDuplicateAction = $rule->on_duplicate;

                $fieldLabels = [];
                foreach ($rule->fields as $fName) {
                    $fieldDef = $block->dataBlock->fields[$fName] ?? null;
                    if ($fieldDef) {
                        $label = !empty($fieldDef->label) ? $fieldDef->label : (!empty($fieldDef->text_original) ? $fieldDef->text_original : $fName);
                        $fieldLabels[] = rtrim($label, ': ');
                    } else {
                        $fieldLabels[] = $fName;
                    }
                }
                $matchedRuleFields = implode(', ', $fieldLabels);

                break; // Stop searching, we found one
            }
        }

        // Action Logic (Create or Handle Duplicate) and performed modifications
        $modificationType = null;
        /** @var FieldModification[] */
        $modifications = [];

        if ($bean === null) {
            // No duplicate, create a new one
            $bean = BeanFactory::newBean($module);
            if (!$bean) {
                return new ActionResult(ResultStatus::ERROR, $actionConfig, "Failed to create a new instance of the module '{$module}'.");
            }
            
            // Assign user if a default one is set
            if (!empty($context->defaultAssignedUserId)) {
                $bean->assigned_user_id = $context->defaultAssignedUserId;
            }
            // Fill all bean fields
            $modifications = $this->populateBean($bean, $block);
            if (property_exists($bean, 'fromAWF')) {
                $bean->fromAWF = true;
            }
            // Inject FK values for outgoing 1-N relationships before save
            $injectedFks = $this->injectRelationFks($context, $actionConfig, $bean, $block);

            // Save without running logic hooks to avoid unwanted side effects in the creation of the record.
            $bean->save(false); 
            
            $modificationType = BeanModificationType::CREATED;

        } else {
            // Duplicate found, apply the rule
            switch ($onDuplicateAction) {
                case OnDuplicateAction::ERROR:
                    // Generate an error and stop the flow
                    return new ActionResult(ResultStatus::ERROR, $actionConfig, "Duplicate record found for module {$module}.");

                case OnDuplicateAction::UPDATE:
                    // Overwrite all fields of the existing bean
                    $modifications = $this->populateBean($bean, $block);
                    $modificationType = BeanModificationType::UPDATED;
                    
                    if (property_exists($bean, 'fromAWF')) {
                        $bean->fromAWF = true;
                    }
                    // Inject FK values for outgoing 1-N relationships before save
                    $injectedFks = $this->injectRelationFks($context, $actionConfig, $bean, $block);

                    // Save without running logic hooks to avoid unwanted side effects in the creation of the record.
                    $bean->save(false); 
                    break;

                case OnDuplicateAction::ENRICH:
                    // Fill only empty fields of the existing bean
                    $modifications = $this->enrichBean($bean, $block); 
                    $modificationType = BeanModificationType::ENRICHED;

                    if (property_exists($bean, 'fromAWF')) {
                        $bean->fromAWF = true;
                    }
                    // Inject FK values for outgoing 1-N relationships before save
                    $injectedFks = $this->injectRelationFks($context, $actionConfig, $bean, $block, true);

                    // Save without running logic hooks to avoid unwanted side effects in the creation of the record.
                    $bean->save(false); 
                    break;
                
                case OnDuplicateAction::SKIP:
                default:
                    // Do nothing, the bean remains as it was
                    $modifications = $this->skipBean($bean, $block);
                    $modificationType = BeanModificationType::SKIPPED;
                    $injectedFks = false;
                    break;
            }
        }

        // Find out if the record has actually been modified
        $hasPhysicalChanges = false;
        foreach ($modifications as $key => $mod) {
            if ($mod->status === FieldModificationStatus::APPLIED) {
                $hasPhysicalChanges = true;
                break;
            }
        }
        if (!$hasPhysicalChanges && in_array($modificationType, [BeanModificationType::UPDATED, BeanModificationType::ENRICHED])) {
            $modificationType = BeanModificationType::UNCHANGED;
        }

        // If FKs were injected and this is a new bean, recalculate the name field
        if (!empty($injectedFks) && $modificationType === BeanModificationType::CREATED) {
            stic_AWF_FormsUtils::recalculateNameIfNeeded($bean, $block, $context);
        }

        // Logging and Return
        $actionResult = new ActionResult(ResultStatus::OK, $actionConfig);
        
        // Register the modification (or non-modification)
        $actionResult->registerBeanModificationFromBlock($bean, $block, $modificationType, $modifications);

        // Set matched rule as metadata
        if (isset($matchedRuleFields) && $matchedRuleFields !== null) {
            $dataToLog = [
                ['key' => 'duplicate_rule_matched', 'label' => $this->translate('DUPLICATE_RULE_MATCHED_TEXT'), 'value' => $matchedRuleFields],
            ];
            $actionResult->registerActionMetadata($bean, $dataToLog);
        }

        // Log injected FK relationships
        if (!empty($injectedFks)) {
            $metadata = [];
            $configsJson = $actionConfig->getResolvedParameter('relation_configs', '');
            if (!empty($configsJson)) {
                $configs = json_decode($configsJson, true);
                if (is_array($configs)) {
                    foreach ($configs as $cfg) {
                        $relName = $cfg['relationship_name'] ?? '';
                        $idName = $cfg['id_name'] ?? '';
                        $targetBlockId = $cfg['target_block_id'] ?? '';
                        $targetBlock = $context->formConfig->data_blocks[$targetBlockId] ?? null;
                        $targetBeanRef = $targetBlock?->getBeanReference();
                        $targetId = $targetBeanRef?->beanId ?? '';
                        $metadata[] = ['key' => 'injected_fk', 'label' => $idName, 'value' => "{$relName} → {$targetId}"];
                    }
                }
            }
            if (!empty($metadata)) {
                $actionResult->registerActionMetadata($bean, $metadata);
            }
        }

        return $actionResult;
    }

    /**
     * Fills a bean with all form data (overwrites).
     * @param SugarBean $bean The bean to update
     * @param DataBlockResolved $block The resolved data block
     * @return array<string, FieldModification> List of modifications indexed by field name
     */
    private function populateBean(SugarBean $bean, DataBlockResolved $block): array
    {
        /** @var FieldModification[] */
        $modifications = [];

        foreach ($block->formData as $fieldName => $fieldResolved) {
            if ($fieldResolved === null) continue;

            $newValue = $fieldResolved->value;
            $fieldDef = $bean->field_defs[$fieldName] ?? null;

            // If it is a related field, the real field that changes in the database is the id_name
            $isRelate = ($fieldDef && isset($fieldDef['type']) && $fieldDef['type'] === 'relate' && !empty($fieldDef['id_name']));
            $targetField = $isRelate ? $fieldDef['id_name'] : $fieldName;

            if (isset($bean->field_defs[$targetField]) && stic_AWF_FormsUtils::isEmailField($bean->field_defs[$targetField], $targetField)) {
                if ($targetField === 'email') {
                    $targetField = 'email1';
                }
                $oldValue = $bean->$targetField ?? null;
            } else {
                $oldValue = isset($bean->$targetField) ? $bean->$targetField : null;
            }
            
            if ($oldValue != $newValue) {
                $bean->$targetField = $newValue;
                $modifications[$targetField] = new FieldModification($targetField, FieldModificationStatus::APPLIED, $newValue, $oldValue);
            } else {
                $modifications[$targetField] = new FieldModification($targetField, FieldModificationStatus::UNCHANGED, $newValue, $oldValue);
            }
        }
        return $modifications;
    }

    /**
     * Fills a bean only with empty fields (enriches).
     * @param SugarBean $bean The bean to enrich
     * @param DataBlockResolved $block The resolved data block
     * @return array<string, FieldModification> List of modifications indexed by field name
     */
    private function enrichBean(SugarBean $bean, DataBlockResolved $block): array
    {
        $modifications = [];

        foreach ($block->formData as $fieldName => $fieldResolved) {
            if ($fieldResolved === null) continue;

            $newValue = $fieldResolved->value;
            $fieldDef = $bean->field_defs[$fieldName] ?? null;

            // If it is a related field, the real field that changes in the database is the id_name
            $isRelate = ($fieldDef && isset($fieldDef['type']) && $fieldDef['type'] === 'relate' && !empty($fieldDef['id_name']));
            $targetField = $isRelate ? $fieldDef['id_name'] : $fieldName;

            $oldValue = isset($bean->$targetField) ? $bean->$targetField : null;
            // Check if the field in the bean is empty or null
            $isEmpty = ($oldValue === null || $oldValue === '' || $oldValue === '^^');

            // Check if the field is boolean (in that case, consider false as empty)
            $isBoolean = ($fieldDef && isset($fieldDef['type']) && ($fieldDef['type'] === 'bool' || $fieldDef['type'] === 'boolean'));
            if ($isBoolean) {
                // Normalize new value to boolean true if it is sent as checked (otherside, consider it false)
                $newValue = ($newValue === true || $newValue === 1 || $newValue === '1');

                // If the field has value, consider empty old value false or null
                if ($newValue) {
                    $isEmpty = ($isEmpty || $oldValue === false || $oldValue === 0 || $oldValue === '0');
                }
            }

            if ($isEmpty && $newValue !== null && $newValue !== '') {
                // The current field is empty.
                $bean->$targetField = $newValue;
                $modifications[$targetField] = new FieldModification($targetField, FieldModificationStatus::APPLIED, $newValue, $oldValue);
                
            } elseif (!$isEmpty && $newValue !== null && $newValue !== '' && $oldValue != $newValue) {
                // The form sends a value but there is already another one
                $modifications[$targetField] = new FieldModification($targetField, FieldModificationStatus::IGNORED_ENRICH, $newValue, $oldValue);
            } else {
                // Both values ​​are equal or null
                $modifications[$targetField] = new FieldModification($targetField, FieldModificationStatus::UNCHANGED, $newValue, $oldValue);
            }
        }

        return $modifications;
    }

    /**
     * Skips a bean 
     * @param SugarBean $bean The bean to skip
     * @param DataBlockResolved $block The resolved data block
     * @return array<string, FieldModification> List of modifications indexed by field name
     */
    private function skipBean(SugarBean $bean, DataBlockResolved $block): array
    {
        $modifications = [];
        foreach ($block->formData as $fieldName => $fieldResolved) {
            if ($fieldResolved === null) continue;
            
            $fieldDef = $bean->field_defs[$fieldName] ?? null;
            $isRelate = ($fieldDef && isset($fieldDef['type']) && $fieldDef['type'] === 'relate' && !empty($fieldDef['id_name']));
            $targetField = $isRelate ? $fieldDef['id_name'] : $fieldName;

            $oldValue = isset($bean->$targetField) ? $bean->$targetField : null;

            $modifications[$targetField] = new FieldModification($targetField, FieldModificationStatus::SKIPPED_DUPLICATE, $fieldResolved->value, $oldValue);
        }
        return $modifications;
    }

    /**
     * Injects FK values for 1-N relationships before the first save.
     * @return bool True if any FK was injected.
     */
    private function injectRelationFks(ExecutionContext $context, FormAction $actionConfig, SugarBean $bean, DataBlockResolved $block, bool $isEnrichMode = false): bool
    {
        $configsJson = $actionConfig->getResolvedParameter('relation_configs', '');
        if (empty($configsJson)) {
            return false;
        }

        $configs = json_decode($configsJson, true);
        if (!is_array($configs) || empty($configs)) {
            return false;
        }

        $isExistingRecord = !empty($bean->id) && !$bean->new_with_id;

        $injectedAny = false;
        foreach ($configs as $config) {
            $idName = $config['id_name'] ?? '';
            $targetBlockId = $config['target_block_id'] ?? '';
            $relationName = $config['relationship_name'] ?? '';

            if (empty($idName) || empty($targetBlockId)) {
                continue;
            }

            $targetBlock = $context->formConfig->data_blocks[$targetBlockId] ?? null;
            if (!$targetBlock) {
                $GLOBALS['log']->warn("SaveRecordAction: Target block '{$targetBlockId}' not found for relationship '{$relationName}'.");
                continue;
            }

            $targetBeanRef = $targetBlock->getBeanReference();
            if (!$targetBeanRef || empty($targetBeanRef->beanId)) {
                $GLOBALS['log']->warn("SaveRecordAction: Target block '{$targetBlock->name}' has no bean ID. Check action order.");
                continue;
            }

            // In enrich mode, protect existing FK values for existing records
            if ($isEnrichMode && $isExistingRecord && !empty($bean->{$idName})) {
                $GLOBALS['log']->debug("SaveRecordAction: Enrich mode — protected existing FK '{$idName}' = '{$bean->{$idName}}'.");
                continue;
            }

            $bean->{$idName} = $targetBeanRef->beanId;
            // Finds and populates the display relate field (e.g. account_name) associated with a physical FK field (e.g. account_id)
            stic_AWF_FormsUtils::populateRelateDisplayField($bean, $idName, $targetBeanRef->beanId);

            $injectedAny = true;
        }

        return $injectedAny;
    }

}
