version: '2'
services:
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_USER=suitecrm
      - MYSQL_DATABASE=suitecrm
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      # We'll need to point this to the directory of mariaDB
      # according to this --
      # https://forums.docker.com/t/how-to-make-mariadb-database-changes-persistent/17339/3
      - 'suite_db_maria:/var/lib/mysql'
  suitecrm:
    build:
      context: ./
      args:
        current_branch: 'silent-installs'
        repository_url: "http://dev2/gitlab/dev/suite-crm"
    image: smt/suitecrm:latest
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=suitecrm
      - SUITECRM_DATABASE_NAME=suitecrm
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8580:80'
      - '8543:443'
    volumes:
      - 'suite_os_data:/certs'
    depends_on:
      - mariadb
volumes:
    suite_os_data:
      driver: local
    suite_db_maria:
      driver: local

