-- Plantilles de notificacions per al mòdul d'ofertes laborals i candidatures
REPLACE INTO email_templates (id,date_entered,date_modified,modified_user_id,created_by,published,name,description,subject,body,body_html,deleted,assigned_user_id,text_only,`type`) VALUES
	-- Oferta laboral - Notificació - Tancament vençut i estat no tancat - Usuari assignat
    ('d3c1d5b7-f8d2-4df4-9f6b-2c63aa6b8e41', NOW(), NOW(), '1', '1', NULL, 'Exemple - Oferta laboral amb tancament vençut sense estat tancada (usuari assignat)', 'Notificació a l''usuari assignat que l''oferta ja ha caducat i no està tancada.', 'Oferta laboral fora de termini:  $stic_job_offers_name', '$stic_job_offers_assigned_user_name:\r\n\r\nL''oferta laboral $stic_job_offers_name té la data de tancament de candidatures vençuda i actualment està en estat $stic_job_offers_status.\r\n\r\nReviseu-la i, si s''escau, actualitzeu-ne l''estat: $sugarurl/index.php?module=stic_Job_Offers&action=DetailView&record=$stic_job_offers_id', '<p>$stic_job_offers_assigned_user_name:</p>\n<p>L''oferta laboral <strong>$stic_job_offers_name</strong> té la data de tancament de candidatures vençuda i actualment està en estat <strong>$stic_job_offers_status</strong>.</p>\n<p><a href="$sugarurl/index.php?module=stic_Job_Offers&action=DetailView&record=$stic_job_offers_id">Reviseu-la</a> i, si s''escau, actualitzeu-ne l''estat.</p>', 0, '1', 0, 'notification'),
    -- Oferta laboral - Notificació - Tancament vençut i estat no tancat - Interlocutor
    ('c2a9e9d1-1f5f-4c6c-9b3c-8d3c2a7f4b81', NOW(), NOW(), '1', '1', NULL, 'Exemple - Oferta laboral amb tancament vençut sense estat tancada (interlocutor)', 'Notificació a l''interlocutor que l''oferta ja ha caducat i no està tancada.', 'Oferta laboral fora de termini: $stic_job_offers_name', 'Benvolgut/da $contact_name:\r\n\r\nL''oferta laboral $stic_job_offers_name té la data de tancament de candidatures vençuda i actualment està en estat $stic_job_offers_status.\r\n\r\nReviseu-la i, si s''escau, actualitzeu-ne l''estat: $portal_address/?internalpage=single_stic_job_offers&action=detail&id=$stic_job_offers_id', '<p>Benvolgut/da $contact_name:</p>\n<p>L''oferta laboral <strong>$stic_job_offers_name</strong> té la data de tancament de candidatures vençuda i actualment està en estat <strong>$stic_job_offers_status</strong>.</p>\n<p><a href="$portal_address/?internalpage=single_stic_job_offers&action=detail&id=$stic_job_offers_id">Reviseu-la</a> i, si s''escau, actualitzeu-ne l''estat.</p>', 0, '1', 0, 'notification'),
    -- Candidatura acceptada - Usuari assignat 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0001', NOW(), NOW(), '1', '1', NULL, 'Exemple - Candidatura acceptada (usuari assignat)', 'Notificació a l''usuari assignat quan una candidatura passa a Acceptada.', 'Candidatura acceptada: $stic_job_applications_stic_job_applications_stic_job_offers_name', '$stic_job_applications_assigned_user_name:\r\n\r\nLa candidatura de $stic_job_applications_stic_job_applications_contacts_name per a l''oferta $stic_job_applications_stic_job_applications_stic_job_offers_name ha estat acceptada.\r\n\r\nEnllaç a la candidatura: $sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id', '<p>$stic_job_applications_assigned_user_name:</p><p>La candidatura de <strong>$stic_job_applications_stic_job_applications_contacts_name</strong> per a l''oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> ha estat <strong>acceptada</strong>.</p><p><a href="$sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id">Enllaç a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Candidatura acceptada - Candidat 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0002', NOW(), NOW(), '1', '1', NULL, 'Exemple - Candidatura acceptada (candidat)', 'Notificació al candidat quan una candidatura passa a Acceptada.', 'Candidatura acceptada: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Benvolgut/da $stic_job_applications_stic_job_applications_contacts_name:\r\n\r\nEns complau informar-vos que la vostra candidatura per a l''oferta $stic_job_applications_stic_job_applications_stic_job_offers_name ha estat Acceptada.\r\n\r\nEnllaç a la candidatura: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Benvolgut/da $stic_job_applications_stic_job_applications_contacts_name:</p><p>Ens complau informar-vos que la vostra candidatura per a l''oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> ha estat <strong>acceptada</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id">Enllaç a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Candidatura rebutjada o tancada - Usuari assignat 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0004', NOW(), NOW(), '1', '1', NULL, 'Exemple - Candidatura rebutjada/tancada (usuari assignat)', 'Notificació a l''usuari assignat quan una candidatura passa a Rebutjada o tancada.', 'Candidatura rebutjada o tancada: $stic_job_applications_stic_job_applications_stic_job_offers_name', '$stic_job_applications_assigned_user_name:\n\nLa candidatura de $stic_job_applications_stic_job_applications_contacts_name per a l''oferta $stic_job_applications_stic_job_applications_stic_job_offers_name ha estat rebutjada.\r\n\r\nEnllaç a la candidatura: $sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id', '<p>$stic_job_applications_assigned_user_name:</p><p>La candidatura de <strong>$stic_job_applications_stic_job_applications_contacts_name</strong> per a l''oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> ha estat rebutjada.</p><p><a href=\"$sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id\">Enllaç a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Candidatura rebutjada o tancada - Candidat 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0005', NOW(), NOW(), '1', '1', NULL, 'Exemple - Candidatura rebutjada/tancada (candidat)', 'Notificació al candidat quan una candidatura passa a Rebutjada o tancada.', 'Candidatura rebutjada: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Benvolgut/da $stic_job_applications_stic_job_applications_contacts_name:\n\nUs agraïm l''interès en l''oferta de $stic_job_applications_stic_job_applications_stic_job_offers_name.\n\nMalauradament, en aquesta ocasió s''ha decidit continuar el procés amb altres candidatures que s''ajusten més a les característiques de l''oferta.\r\n\r\nEnllaç a la candidatura: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Benvolgut/da $stic_job_applications_stic_job_applications_contacts_name:</p><p>Us agraïm l''interès en l''oferta de <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong>.</p><p>Malauradament, en aquesta ocasió s''ha decidit continuar el procés amb altres candidatures que s''ajusten més a les característiques de l''oferta</p><p><a href=\"$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id\">Enllaç a la candidatura</a>.</p><p>Et desitgem molt d èxit. Atentament, $stic_job_offers_stic_job_offers_accounts_name</p>', 0, '1', 0, 'notification'),
    -- Candidatura altres estats - Usuari assignat 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0007', NOW(), NOW(), '1', '1', NULL, 'Exemple - Candidatura altres estats (usuari assignat)', 'Notificació a l''usuari assignat quan una candidatura passa a Pendent entrevista o Entrevistada.', 'Candidatura $stic_job_applications_status: $stic_job_applications_stic_job_applications_stic_job_offers_name', '$stic_job_applications_assigned_user_name:\r\n\r\nLa candidatura de $stic_job_applications_stic_job_applications_contacts_name per a l''oferta $stic_job_applications_stic_job_applications_stic_job_offers_name ha canviat a $stic_job_applications_status.\r\n\r\nEnllaç a la candidatura: $sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id', '<p>$stic_job_applications_assigned_user_name,</p><p>La candidatura de <strong>$stic_job_applications_stic_job_applications_contacts_name</strong> per a l''oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> ha canviat a <strong>$stic_job_applications_status</strong>.</p><p><a href="$sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id">Enllaç a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Candidatura altres estats - Candidat 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0008', NOW(), NOW(), '1', '1', NULL, 'Exemple - Candidatura altres estats (candidat)', 'Notificació al candidat quan una candidatura passa a Pendent entrevista o Entrevistada.', 'Candidatura $stic_job_applications_status: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Benvolgut/da $stic_job_applications_stic_job_applications_contacts_name:\r\n\r\nLa vostra candidatura per a l''oferta $stic_job_applications_stic_job_applications_stic_job_offers_name ha canviat a $stic_job_applications_status.\r\n\r\nEnllaç a la candidatura: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Benvolgut/da $stic_job_applications_stic_job_applications_contacts_name:</p><p>La vostra candidatura per a l''oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> ha canviat a <strong>$stic_job_applications_status</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id">Enllaç a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Oferta - Canvi d''estat - Usuari assignat 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0010', NOW(), NOW(), '1', '1', NULL, 'Exemple - Canvi d''estat d''oferta laboral (usuari assignat)', 'Notificació a l''usuari assignat del canvi d''estat d''una oferta.', 'Canvi d''estat de l''oferta: $stic_job_offers_name', '$stic_job_offers_assigned_user_name:\r\n\r\nL''oferta $stic_job_offers_name ha canviat a $stic_job_offers_status.\r\n\r\nEnllaç a l''oferta: $sugarurl/index.php?module=stic_Job_Offers&action=DetailView&record=$stic_job_offers_id', '<p>$stic_job_offers_assigned_user_name:</p><p>L''oferta <strong>$stic_job_offers_name</strong> ha canviat a <strong>$stic_job_offers_status</strong>.</p><p><a href="$sugarurl/index.php?module=stic_Job_Offers&action=DetailView&record=$stic_job_offers_id">Enllaç a l''oferta</a>.</p>', 0, '1', 0, 'notification'),
    -- Oferta - Canvi d''estat - Candidats 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0011', NOW(), NOW(), '1', '1', NULL, 'Exemple - Canvi d''estat d''oferta laboral (candidats)', 'Notificació als candidats del canvi d''estat d''una oferta.', 'Canvi d''estat de l''oferta: $stic_job_offers_name', 'Benvolgut/da:\r\n\r\nL''oferta $stic_job_offers_name ha canviat a $stic_job_offers_status.\r\n\r\nEnllaç a l''oferta: $portal_address/?internalpage=single_stic_job_offers&action=detail&id=$stic_job_offers_id', '<p>Benvolgut/da:</p><p>L''oferta <strong>$stic_job_offers_name</strong> ha canviat a <strong>$stic_job_offers_status</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_offers&action=detail&id=$stic_job_offers_id">Enllaç a l''oferta</a>.</p>', 0, '1', 0, 'notification'),
    -- Oferta - Canvi d'estat - Interlocutor 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0012', NOW(), NOW(), '1', '1', NULL, 'Exemple - Canvi d''estat d''oferta laboral (interlocutor)', 'Notificació a l''interlocutor del canvi d''estat d''una oferta.', 'Canvi d''estat de l''oferta: $stic_job_offers_name', 'Benvolgut/da $contact_name:\r\n\r\nL''oferta $stic_job_offers_name ha canviat a $stic_job_offers_status.\r\n\r\nEnllaç a l''oferta: $portal_address/?internalpage=single_stic_job_offers&action=detail&id=$stic_job_offers_id', '<p>Benvolgut/da $contact_name:</p><p>L''oferta <strong>$stic_job_offers_name</strong> ha canviat a <strong>$stic_job_offers_status</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_offers&action=detail&id=$stic_job_offers_id">Enllaç a l''oferta</a>.</p>', 0, '1', 0, 'notification'),
    -- Àrea Privada - Credencials d''accés - Persona
    ('6e6f5a91-2cb9-4f42-bf26-0a13b2f1c101', NOW(), NOW(), '1', '1', NULL, 'Exemple - Credencials d''accés a l''àrea privada (persona)', 'Notificació de les credencials d''accés a l''àrea privada quan s''activa l''accés d''una persona.', 'Les vostres credencials d''accés a l''àrea privada', '$contacts_name:\r\n\r\nJa teniu habilitat l''accés a l''àrea privada.\r\n\r\nUsuari: $contacts_stic_pa_username_c\r\nContrasenya: $contacts_stic_pa_password_c\r\n\r\nHi podeu accedir a l''adreça: $portal_address', '<p>$contacts_name:</p><p>Ja teniu habilitat l''accés a l''àrea privada.</p><p><strong>Usuari:</strong> $contacts_stic_pa_username_c<br><strong>Contrasenya:</strong> $contacts_stic_pa_password_c</p><p>Hi podeu accedir a l''adreça: <a href="$portal_address">$portal_address</a></p>', 0, '1', 0, 'notification'),
    -- Àrea Privada - Credencials d''accés - Compte
    ('6e6f5a91-2cb9-4f42-bf26-0a13b2f1c102', NOW(), NOW(), '1', '1', NULL, 'Exemple - Credencials d''accés a l''àrea privada (organització)', 'Notificació de les credencials d''accés a l''àrea privada quan s''activa l''accés d''una organització.', 'Les vostres credencials d''accés a l''àrea privada', '$accounts_name:\r\n\r\nJa teniu habilitat l''accés a l''àrea privada.\r\n\r\nUsuari: $accounts_stic_pa_username_c\r\nContrasenya: $accounts_stic_pa_password_c\r\n\r\nHi podeu accedir a l''adreça: $portal_address\r\n\r\n', '<p>$accounts_name:</p><p>Ja teniu habilitat l''accés a l''àrea privada.</p><p><strong>Usuari:</strong> $accounts_stic_pa_username_c<br><strong>Contrasenya:</strong> $accounts_stic_pa_password_c</p><p>Hi podeu accedir a l''adreça: <a href="$portal_address">$portal_address</a></p>', 0, '1', 0, 'notification'),
    -- Candidatures - Notificació - Nova candidatura
    ('7a9f8f3a-2d1f-4a40-9dd6-7c6f9e1b7001', NOW(), NOW(), '1', '1', NULL, 'Exemple - Candidatura creada (usuari assignat)', 'Notificació a l''usuari assignat quan es presenta una nova candidatura.', 'Nova candidatura rebuda: $stic_job_applications_stic_job_applications_stic_job_offers_name', '$stic_job_applications_assigned_user_name:\r\n\r\n$stic_job_applications_stic_job_applications_contacts_name ha presentat la seva candidatura a l''oferta $stic_job_applications_stic_job_applications_stic_job_offers_name.\r\n\r\nEnllaç a la candidatura: $sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id', '<p>$stic_job_applications_assigned_user_name:</p><p><strong>$stic_job_applications_stic_job_applications_contacts_name</strong> ha presentat la seva candidatura a l''oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong>.</p><p><a href=\"$sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id\">Enllaç a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Candidatures - Notificació - Candidatura registrada (candidat)
    ('7a9f8f3a-2d1f-4a40-9dd6-7c6f9e1b7003', NOW(), NOW(), '1', '1', NULL, 'Exemple - Candidatura creada (candidat)', 'Notificació al candidat que la seva candidatura ha estat registrada.', 'Candidatura rebuda: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Benvolgut/da $stic_job_applications_stic_job_applications_contacts_name:\r\n\r\nHem rebut la vostra candidatura per a l''oferta $stic_job_applications_stic_job_applications_stic_job_offers_name.\r\n\r\nEnllaç a la candidatura: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Benvolgut/da $stic_job_applications_stic_job_applications_contacts_name:</p><p>Hem rebut la vostra candidatura per a l''oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong>.</p><p><a href=\"$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id\">Enllaç a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Missatge - Notificació - Nou missatge en conversa
    ('7a9f8f3a-2d1f-4a40-9dd6-7c6f9e1b7002', NOW(), NOW(), '1', '1', NULL, 'Exemple - Nou missatge en conversa (usuari assignat)', 'Notificació a l''usuari assignat quan un usuari de l''àrea privada emet un missatge en una conversa.', 'Nou missatge rebut', '$stic_messages_assigned_user_name:\r\n\r\nHeu rebut un missatge d''una conversa de l''àrea privada.\r\n\r\nConversa:\r\n$stic_conversations_subject\r\n\r\nMissatge:\r\n$stic_messages_message\r\n\r\nEnllaç al missatge: $sugarurl/index.php?module=stic_Messages&action=DetailView&record=$stic_messages_id', '<p>$stic_messages_assigned_user_name:</p><p>Heu rebut un missatge d''una conversa de l''àrea privada.</p><p><strong>Conversa:</strong><br>$stic_conversations_subject</p><p><strong>Missatge:</strong><br>$stic_messages_message</p><p><a href=\"$sugarurl/index.php?module=stic_Messages&action=DetailView&record=$stic_messages_id\">Enllaç al missatge</a>.</p>', 0, '1', 0, 'notification'),
    -- Ofertes laborals - Notificació - Nova oferta laboral (usuari assignat)
    ('3c0a5f6e-1111-4f8a-9a11-3b1b7c2a0101', NOW(), NOW(), '1', '1', NULL, 'Exemple - Nova oferta laboral (usuari assignat)', 'Notificació a l''usuari assignat de la creació d''una oferta laboral.', 'Oferta creada: $stic_job_offers_name', '$stic_job_offers_assigned_user_name:\r\n\r\nS''ha creat una nova oferta laboral: $stic_job_offers_name.\r\n\r\nEnllaç a l''oferta: $sugarurl/index.php?module=stic_Job_Offers&action=DetailView&record=$stic_job_offers_id', '<p>$stic_job_offers_assigned_user_name:</p><p>S''ha creat una nova oferta laboral: <strong>$stic_job_offers_name</strong>.</p><p><a href="$sugarurl/index.php?module=stic_Job_Offers&action=DetailView&record=$stic_job_offers_id">Enllaç a l''oferta</a>.</p>', 0, '1', 0, 'notification'),
    -- Missatge - Notificació - Nou missatge en conversa (persona relacionada)
    ('7a9f8f3a-2d1f-4a40-9dd6-7c6f9e1b7004', NOW(), NOW(), '1', '1', NULL, 'Exemple - Nou missatge en conversa (usuari de l''àrea privada)', 'Notificació a l''usuari de l''àrea privada quan l''usuari assignat emet un missatge en una conversa.', 'Nou missatge rebut', 'Benvolgut/da $contact_name:\r\n\r\nHeu rebut un missatge a l''àrea privada.\r\n\r\nConversa:\r\n$stic_conversations_subject\r\n\r\nMissatge:\r\n$stic_messages_message\r\n\r\nEl podeu consultar i respondre a l''àrea privada: $portal_address/?internalpage=single_stic_chat&action=detail&id=$stic_conversations_id', '<p>Benvolgut/da $contact_name:</p><p>Heu rebut un missatge a l''àrea privada.</p><p><strong>Conversa:</strong><br>$stic_conversations_subject</p><p><strong>Missatge:</strong><br>$stic_messages_message</p><p>El podeu consultar i respondre a l''àrea privada: <a href="$portal_address/?internalpage=single_stic_chat&action=detail&id=$stic_conversations_id">$portal_address</a>.</p>', 0, '1', 0, 'notification'),
    -- Candidatures - Notificació - Candidatura presentada (interlocutor)
    ('4f2c7b91-0c3e-4a2b-9b3e-7c4a9b1e9001', NOW(), NOW(), '1', '1', NULL, 'Exemple - Candidatura presentada (interlocutor)', 'Notificació a l''interlocutor quan una candidatura passa a Presentada.', 'Candidatura presentada: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Benvolgut/da $contact_name:\r\n\r\n$stic_job_applications_stic_job_applications_contacts_name ha presentat la seva candidatura a l''oferta $stic_job_applications_stic_job_applications_stic_job_offers_name.\r\n\r\nEnllaç a la candidatura: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Benvolgut/da $contact_name:</p><p><strong>$stic_job_applications_stic_job_applications_contacts_name</strong> ha presentat la seva candidatura a l''oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id">Enllaç a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Candidatures - Notificació - Candidatura acceptada (interlocutor)
    ('4f2c7b91-0c3e-4a2b-9b3e-7c4a9b1e9010', NOW(), NOW(), '1', '1', NULL, 'Exemple - Candidatura acceptada (interlocutor)', 'Notificació a l''interlocutor quan una candidatura passa a Acceptada.', 'Candidatura acceptada: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Benvolgut/da $contact_name:\r\n\r\nLa candidatura de $stic_job_applications_stic_job_applications_contacts_name per a l''oferta $stic_job_applications_stic_job_applications_stic_job_offers_name ha estat acceptada.\r\n\r\nEnllaç a la candidatura: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Benvolgut/da $contact_name:</p><p>La candidatura de <strong>$stic_job_applications_stic_job_applications_contacts_name</strong> per a l''oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> ha estat <strong>acceptada</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id">Enllaç a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Candidatures - Notificació - Candidatura rebutjada o tancada (interlocutor)
    ('4f2c7b91-0c3e-4a2b-9b3e-7c4a9b1e9011', NOW(), NOW(), '1', '1', NULL, 'Exemple - Candidatura rebutjada/tancada (interlocutor)', 'Notificació a l''interlocutor quan una candidatura passa a Rebutjada o tancada.', 'Candidatura rebutjada o tancada: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Benvolgut/da $contact_name:\r\n\r\nLa candidatura de $stic_job_applications_stic_job_applications_contacts_name per a l''oferta $stic_job_applications_stic_job_applications_stic_job_offers_name ha estat rebutjada o tancada.\r\n\r\nEnllaç a la candidatura: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Benvolgut/da $contact_name:</p><p>La candidatura de <strong>$stic_job_applications_stic_job_applications_contacts_name</strong> per a l''oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> ha estat <strong>Rebutjada o tancada</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id">Enllaç a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Candidatures - Notificació - Candidatura cancel·lada al portal (usuari assignat)
    ('4f2c7b91-0c3e-4a2b-9b3e-7c4a9b1e9002', NOW(), NOW(), '1', '1', NULL, 'Exemple - Candidatura cancel·lada (usuari assignat)', 'Notificació a l''usuari assignat quan es cancel·la una candidatura.', 'Candidatura cancel·lada: $stic_job_applications_stic_job_applications_stic_job_offers_name', '$stic_job_applications_assigned_user_name:\r\n\r\n$stic_job_applications_stic_job_applications_contacts_name ha cancel·lat la seva candidatura per a l''oferta $stic_job_applications_stic_job_applications_stic_job_offers_name.\r\n\r\nEnllaç a la candidatura: $sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id', '<p>$stic_job_applications_assigned_user_name:</p><p><strong>$stic_job_applications_stic_job_applications_contacts_name</strong> ha cancel·lat la seva candidatura per a l''oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong>.</p><p><a href="$sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id">Enllaç a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Candidatures - Notificació - Candidatura cancel·lada al portal (persona relacionada)
    ('4f2c7b91-0c3e-4a2b-9b3e-7c4a9b1e9003', NOW(), NOW(), '1', '1', NULL, 'Exemple - Candidatura cancel·lada (interlocutor)', 'Notificació a l''interlocutor quan es cancel·la una candidatura.', 'Candidatura cancel·lada: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Benvolgut/da $contact_name:\r\n\r\n$stic_job_applications_stic_job_applications_contacts_name ha cancel·lat la seva candidatura per a l''oferta $stic_job_applications_stic_job_applications_stic_job_offers_name.\r\n\r\nEnllaç a la candidatura: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Benvolgut/da $contact_name:</p><p><strong>$stic_job_applications_stic_job_applications_contacts_name</strong> ha cancel·lat la seva candidatura per a l''oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id">Enllaç a la candidatura</a>.</p>', 0, '1', 0, 'notification');

-- Ofertes laborals - Notificació - Nova oferta (usuari assignat)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('3c0a5f6e-0001-4f8a-9a11-3b1b7c2a0200', 'Ofertes laborals - Notificació - Nova oferta (usuari assignat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flux de treball que envia una notificació a l''usuari assignat quan algú altre crea una oferta laboral.', 0, '1', 'stic_Job_Offers', 'New_Records', 'Inactive', 'On_Save', 0, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('00000bd1-6280-6302-56a9-69fb0de58e31', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3c0a5f6e-0001-4f8a-9a11-3b1b7c2a0200', 1, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'assigned_user_name', 'Not_Equal_To', 'Field', 'created_by_name');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('3c0a5f6e-0001-4f8a-9a11-3b1b7c2a0201', 'Enviament de notificació (usuari assignat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3c0a5f6e-0001-4f8a-9a11-3b1b7c2a0200', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiM2MwYTVmNmUtMTExMS00ZjhhLTlhMTEtM2IxYjdjMmEwMTAxIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxODoiYXNzaWduZWRfdXNlcl9saW5rIjt9fQ==');

-- Ofertes laborals - Notificació - Data de tancament vençuda sense estat tancada (usuari assignat)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('000009c0-3302-dbf2-c1b7-69a850a8b6d5', 'Ofertes laborals - Notificació - Data de tancament (usuari assignat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flux de treball que envia una notificació a l''usuari assignat quan la data de tancament d''una oferta és el dia anterior i no té estat Tancada.', 0, '1', 'stic_Job_Offers', 'All_Records', 'Inactive', 'In_Scheduler', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('000000cd-0341-b540-66b5-69a8502ff15d', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000009c0-3302-dbf2-c1b7-69a850a8b6d5', 3, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'assigned_user_name', 'Not_Equal_To', 'Value', NULL),
('000002a2-0646-1de2-e72c-69a85088e3cf', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000009c0-3302-dbf2-c1b7-69a850a8b6d5', 1, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'applications_end_date', 'Equal_To', 'Date', 'YTo0OntpOjA7czo1OiJ0b2RheSI7aToxO3M6NToibWludXMiO2k6MjtzOjE6IjEiO2k6MztzOjM6ImRheSI7fQ=='),
('000003b5-2bb2-8999-84b6-69a850918ce2', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000009c0-3302-dbf2-c1b7-69a850a8b6d5', 2, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'status', 'Not_Equal_To', 'Multi', '^closed_covered^,^closed_partially_covered^,^closed_not_covered^');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000727-a7fd-96e4-64fa-69a850c229f5', 'Enviament de notificació (usuari assignat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000009c0-3302-dbf2-c1b7-69a850a8b6d5', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIwIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiZDNjMWQ1YjctZjhkMi00ZGY0LTlmNmItMmM2M2FhNmI4ZTQxIjtzOjEzOiJvdXRib3VuZF9zbXRwIjtzOjY6InN5c3RlbSI7czoxNToiZnJvbV9lbWFpbF9uYW1lIjtzOjA6IiI7czoxODoiZnJvbV9lbWFpbF9hZGRyZXNzIjtzOjA6IiI7czoxMzoicmVwbHlfdG9fbmFtZSI7czowOiIiO3M6ODoicmVwbHlfdG8iO3M6MDoiIjtzOjEzOiJlbWFpbF90b190eXBlIjthOjE6e2k6MDtzOjI6InRvIjt9czoxNzoiZW1haWxfdGFyZ2V0X3R5cGUiO2E6MTp7aTowO3M6MTM6IlJlbGF0ZWQgRmllbGQiO31zOjU6ImVtYWlsIjthOjE6e2k6MDtzOjE4OiJhc3NpZ25lZF91c2VyX2xpbmsiO319');

-- Ofertes laborals - Notificació - Data de tancament vençuda sense estat tancada (interlocutor)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000815-c8ac-f000-0454-69fb1eb45882', 'Ofertes laborals - Notificació - Data de tancament (interlocutor)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flux de treball que envia una notificació a l''interlocutor quan la data de tancament d''una oferta és el dia anterior i no té estat Tancada.', 0, '1', 'stic_Job_Offers', 'All_Records', 'Inactive', 'In_Scheduler', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('000002f1-b9de-d1e8-df06-69fb1eaaa748', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000815-c8ac-f000-0454-69fb1eb45882', 1, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'applications_end_date', 'Equal_To', 'Date', 'YTo0OntpOjA7czo1OiJ0b2RheSI7aToxO3M6NToibWludXMiO2k6MjtzOjE6IjEiO2k6MztzOjM6ImRheSI7fQ=='),
('00000a88-3ede-584f-ae0e-69fb1eed8a19', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000815-c8ac-f000-0454-69fb1eb45882', 3, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'interlocutor', 'Not_Equal_To', 'Value', NULL),
('00000cec-1ccd-0c68-a46d-69fb1e96bc1c', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000815-c8ac-f000-0454-69fb1eb45882', 2, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'status', 'Not_Equal_To', 'Multi', '^closed_covered^,^closed_partially_covered^,^closed_not_covered^');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000338-84ca-31fe-96f1-69fb1e28a9db', 'Enviament de notificació (interlocutor)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000815-c8ac-f000-0454-69fb1eb45882', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIwIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiYzJhOWU5ZDEtMWY1Zi00YzZjLTliM2MtOGQzYzJhN2Y0YjgxIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxMjoiaW50ZXJsb2N1dG9yIjt9fQ==');

-- Candidatures - Notificació - Nova candidatura (usuari assignat / candidat)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a101', 'Candidatures - Notificació - Nova candidatura (usuari assignat / candidate)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flux de treball que envia una notificació a l''usuari assignat quan un tercer (un potencial candidat o un altre usuari del CRM) crea una candidatura. El candidat també en rep confirmació.', 0, '1', 'stic_Job_Applications', 'New_Records', 'Inactive', 'On_Save', 0, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('0000043a-c7f6-133c-4b52-69fb5600df06', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a101', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'created_by_name', 'Not_Equal_To', 'Field', 'assigned_user_name'),
('0000047a-f4b7-3937-dff0-69d8c03ca9bd', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a101', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'review');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a103', 'Enviament de notificació (usuari assignat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a101', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiN2E5ZjhmM2EtMmQxZi00YTQwLTlkZDYtN2M2ZjllMWI3MDAxIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxODoiYXNzaWduZWRfdXNlcl9saW5rIjt9fQ=='),
('2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a104', 'Enviament de notificació (candidat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a101', 2, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiN2E5ZjhmM2EtMmQxZi00YTQwLTlkZDYtN2M2ZjllMWI3MDAzIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MzA6InN0aWNfam9iX2FwcGxpY2F0aW9uc19jb250YWN0cyI7fX0=');

-- Candidatures - Notificació - Nova candidatura (candidat)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('000006a9-afb9-d96f-0c92-69fb56113842', 'Candidatures - Notificació - Nova candidatura (candidat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flux de treball que envia una notificació al candidat quan l''usuari assignat crea una candidatura en el seu nom.', 0, '1', 'stic_Job_Applications', 'New_Records', 'Inactive', 'On_Save', 0, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('0000074b-8f66-a4cf-721f-69fb56d5b469', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000006a9-afb9-d96f-0c92-69fb56113842', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'created_by_name', 'Equal_To', 'Field', 'assigned_user_name'),
('0000095f-fb16-acd0-9a04-69fb56f0038e', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000006a9-afb9-d96f-0c92-69fb56113842', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'review');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000958-87e6-f511-43f9-69fb56e5893a', 'Enviament de notificació (candidat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000006a9-afb9-d96f-0c92-69fb56113842', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiN2E5ZjhmM2EtMmQxZi00YTQwLTlkZDYtN2M2ZjllMWI3MDAzIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czozMDoic3RpY19qb2JfYXBwbGljYXRpb25zX2NvbnRhY3RzIjt9fQ==');

-- Candidatures - Notificació - Presentada (candidat)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000f20-7b3a-4a1b-8f2a-69a830ec33d0', 'Candidatures - Notificació - Presentada (candidat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flux de treball que envia una notificació al candidat quan una candidatura passa a estat Presentada.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('00000f21-7b3a-4a1b-8f2a-69a830ec33d0', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000f20-7b3a-4a1b-8f2a-69a830ec33d0', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'presented'),
('00000f22-7b3a-4a1b-8f2a-69a830ec33d0', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000f20-7b3a-4a1b-8f2a-69a830ec33d0', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL);
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000f23-7b3a-4a1b-8f2a-69a830ec33d0', 'Enviament de notificació (candidat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000f20-7b3a-4a1b-8f2a-69a830ec33d0', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA4IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MzA6InN0aWNfam9iX2FwcGxpY2F0aW9uc19jb250YWN0cyI7fX0=');

-- Candidatures - Notificació - Acceptada (usuari assignat / candidat)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000190-75e4-3e38-5f8f-69a82fb83c15', 'Candidatures - Notificació - Acceptada (usuari assignat / candidat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flux de treball que envia una notificació a l''usuari assignat i al candidat quan un tercer (l''interlocutor extern o un altre usuari del CRM) canvia una candidatura a Acceptada.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('000003b6-1b3f-4bc3-b4f5-69a82f8345f3', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000190-75e4-3e38-5f8f-69a82fb83c15', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'accepted'),
('00000778-cf26-a3ea-ab3c-69fb592f7d71', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000190-75e4-3e38-5f8f-69a82fb83c15', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Not_Equal_To', 'Field', 'assigned_user_name'),
('00000f10-1111-2222-3333-69a82fb83c15', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000190-75e4-3e38-5f8f-69a82fb83c15', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL);
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('000009bf-d247-6e61-ac71-69a82f5103df', 'Enviament de notificació (usuari assignat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000190-75e4-3e38-5f8f-69a82fb83c15', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDAxIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MTg6ImFzc2lnbmVkX3VzZXJfbGluayI7fX0='),
('000009c1-d247-6e61-ac71-69a82f5103d1', 'Enviament de notificació (candidat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000190-75e4-3e38-5f8f-69a82fb83c15', 2, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDAyIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MzA6InN0aWNfam9iX2FwcGxpY2F0aW9uc19jb250YWN0cyI7fX0=');

-- Candidatures - Notificació - Acceptada (candidat)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000101-4d1c-b7e4-7fc4-69fb5af86cfa', 'Candidatures - Notificació - Acceptada (candidat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flux de treball que envia una notificació al candidat quan l''usuari assignat canvia una candidatura a Acceptada.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('0000054f-feaa-42b0-ba34-69fb5a7a4d76', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000101-4d1c-b7e4-7fc4-69fb5af86cfa', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Equal_To', 'Field', 'assigned_user_name'),
('00000876-3720-e155-6d3a-69fb5aaf478a', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000101-4d1c-b7e4-7fc4-69fb5af86cfa', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL),
('00000b3c-676c-7b20-3da5-69fb5abe6397', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000101-4d1c-b7e4-7fc4-69fb5af86cfa', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'accepted');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('000007cf-9d70-dd55-61c1-69fb5adc6f5b', 'Enviament de notificació (candidat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000101-4d1c-b7e4-7fc4-69fb5af86cfa', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDAyIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czozMDoic3RpY19qb2JfYXBwbGljYXRpb25zX2NvbnRhY3RzIjt9fQ==');

-- Candidatures - Notificació - Rebutjada o tancada (usuari assignat / candidat)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000ace-02d2-2425-107e-69a82a9eacb5', 'Candidatures - Notificació - Rebutjada o tancada (usuari assignat / candidat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flux de treball que envia una notificació a l''usuari assignat i al candidat quan un tercer (l''interlocutor extern o un altre usuari del CRM) canvia una candidatura a Rebutjada o tancada.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('000001a5-41d3-7d65-fe58-69a82a22be9d', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'rejected_closed'),
('00000bb2-129d-3cff-4d79-69fb5a5c974d', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 4, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Not_Equal_To', 'Field', 'assigned_user_name'),
('00000f11-1111-2222-3333-69a82a9eacb5', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL),
('00000f14-7b3a-4a1b-8f2a-69a82a9eacb6', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'rejection_reason', 'Not_Equal_To', 'Value', 'resignation');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000b52-cd9a-161e-c7d1-69a82a27d7fb', 'Enviament de notificació (usuari assignat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA0IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MTg6ImFzc2lnbmVkX3VzZXJfbGluayI7fX0='),
('00000b53-cd9a-161e-c7d1-69a82a27d7f1', 'Enviament de notificació (candidat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 2, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA1IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MzA6InN0aWNfam9iX2FwcGxpY2F0aW9uc19jb250YWN0cyI7fX0=');

-- Candidatures - Notificació - Rebutjada o tancada (candidat)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('000001be-e27b-e9a6-98aa-69fb5a33138a', 'Candidatures - Notificació - Rebutjada o tancada (Canviat per Usuari assignat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flux de treball que envia una notificació al candidat quan l''usuari assignat canvia una candidatura a Rebutjada o tancada.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('00000181-a6bf-cbe4-a82a-69fb5ae259c6', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000001be-e27b-e9a6-98aa-69fb5a33138a', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL),
('00000214-51dc-4a76-e116-69fb5a064799', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000001be-e27b-e9a6-98aa-69fb5a33138a', 4, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Equal_To', 'Field', 'assigned_user_name'),
('00000849-bf4b-beca-85d7-69fb5a80dc0e', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000001be-e27b-e9a6-98aa-69fb5a33138a', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'rejection_reason', 'Not_Equal_To', 'Value', 'resignation'),
('000009d7-2129-6ea1-ff80-69fb5acbdca7', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000001be-e27b-e9a6-98aa-69fb5a33138a', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'rejected_closed');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('0000085b-5ed1-39bc-6fc1-69fb5a995e7a', 'Enviament de notificació (candidat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000001be-e27b-e9a6-98aa-69fb5a33138a', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA1IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czozMDoic3RpY19qb2JfYXBwbGljYXRpb25zX2NvbnRhY3RzIjt9fQ==');

-- Candidatures - Notificació - Altres estats (usuari assignat / candidat)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000174-497a-ef41-5ae8-69a830ec33ce', 'Candidatures - Notificació - Altres estats (usuari assignat / candidat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flux de treball que envia una notificació a l''usuari assignat i al candidat quan un tercer (l''interlocutor extern o un altre usuari del CRM) canvia una candidatura als estats Pendent entrevista o Entrevistada.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('0000033d-8ae0-fe4a-64ba-69a830439caf', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000174-497a-ef41-5ae8-69a830ec33ce', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Multi', '^pending_interview^,^interviewed^'),
('00000603-e27d-aab5-227a-69fb24be4977', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000174-497a-ef41-5ae8-69a830ec33ce', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Not_Equal_To', 'Field', 'assigned_user_name'),
('00000f12-1111-2222-3333-69a830ec33ce', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000174-497a-ef41-5ae8-69a830ec33ce', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL);
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000b79-f2fc-034b-4bb2-69a830fb223b', 'Enviament de notificació (usuari assignat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000174-497a-ef41-5ae8-69a830ec33ce', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA3IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxODoiYXNzaWduZWRfdXNlcl9saW5rIjt9fQ=='),
('00000b80-f2fc-034b-4bb2-69a830fb2240', 'Enviament de notificació (candidat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000174-497a-ef41-5ae8-69a830ec33ce', 2, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA4IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czozMDoic3RpY19qb2JfYXBwbGljYXRpb25zX2NvbnRhY3RzIjt9fQ==');

-- Candidatures - Notificació - Altres estats (candidat)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('000003e0-ebe2-ff1f-40d2-69fb278f5ab6', 'Candidatures - Notificació - Altres estats (candidat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flux de treball que envia una notificació al candidat quan l''usuari assignat canvia l''estat d''una candidatura als estats Pendent entrevista o Entrevistada.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('00000026-e7ad-3c88-57b0-69fb27298480', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000003e0-ebe2-ff1f-40d2-69fb278f5ab6', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Equal_To', 'Field', 'assigned_user_name'),
('0000019e-3313-a824-8459-69fb275e68a5', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000003e0-ebe2-ff1f-40d2-69fb278f5ab6', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL),
('00000bcb-699f-9731-d947-69fb27e8ef59', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000003e0-ebe2-ff1f-40d2-69fb278f5ab6', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Multi', '^pending_interview^,^interviewed^');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000225-589a-fac8-0b73-69fb275b376d', 'Enviament de notificació (candidat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000003e0-ebe2-ff1f-40d2-69fb278f5ab6', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA4IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czozMDoic3RpY19qb2JfYXBwbGljYXRpb25zX2NvbnRhY3RzIjt9fQ==');

-- Missatges - Notificació - Nou missatge (usuari assignat)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b201', 'Missatges - Notificació - Nou missatge (usuari assignat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flux de treball que envia una notificació a l''usuari assignat quan un usuari de l''àrea privada (interlocutor o candidat) emet un missatge en una conversa.', 0, '1', 'stic_Messages', 'New_Records', 'Inactive', 'On_Save', 0, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b202', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b201', 1, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'type', 'Equal_To', 'Value', 'private_area'),
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b203', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b201', 2, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'status', 'Equal_To', 'Value', 'sent'),
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b204', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b201', 3, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'parent_type', 'Equal_To', 'Value', 'Contacts');
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b206', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b201', 4, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'direction', 'Equal_To', 'Value', 'inbound');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b205', 'Enviament de notificació (usuari assignat)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b201', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiN2E5ZjhmM2EtMmQxZi00YTQwLTlkZDYtN2M2ZjllMWI3MDAyIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxODoiYXNzaWduZWRfdXNlcl9saW5rIjt9fQ==');

-- Missatges - Notificació - Nou missatge (usuari de l'àrea privada)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b210', 'Missatges - Notificació - Nou missatge (usuari de l''àrea privada)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flux de treball que envia una notificació a l''usuari de l''àrea privada (interlocutor o candidat) quan l''usuari assignat emet un missatge en una conversa.', 0, '1', 'stic_Messages', 'New_Records', 'Inactive', 'On_Save', 0, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b212', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b210', 1, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'type', 'Equal_To', 'Value', 'private_area'),
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b213', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b210', 2, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'status', 'Equal_To', 'Value', 'sent'),
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b214', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b210', 3, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'parent_type', 'Equal_To', 'Value', 'Contacts'),
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b215', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b210', 4, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'direction', 'Equal_To', 'Value', 'outbound');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b211', 'Enviament de notificació (usuari de l''àrea privada)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b210', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiN2E5ZjhmM2EtMmQxZi00YTQwLTlkZDYtN2M2ZjllMWI3MDA0IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxOToicGFyZW50X2NvbnRhY3RfbmFtZSI7fX0=');

-- Configuraciò per a l'enviament de credencials de l'Àrea Privada
REPLACE INTO `stic_settings` (`id`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `deleted`, `assigned_user_id`, `type`, `name`, `value`, `description`) VALUES
('f8b4a3a2-9f40-4c2e-9f8d-5e76a20f5d11', NOW(), NOW(), '1', '1', 0, '1', 'PRIVATEAREA', 'PRIVATEAREA_SEND_CREDENTIALS_ON_ENABLE', '0', 'Indica si s''enviaran automàticament les credencials de l''Àrea Privada en marcar el camp "Activa l''Àrea Privada" dels mòduls Persones i Organitzacions (0 = No (valor per defecte), 1 = Sí).'),
('4ef9497d-6511-4a87-9467-01ca8ac99f20', NOW(), NOW(), '1', '1', 0, '1', 'PRIVATEAREA', 'PRIVATEAREA_CREDENTIALS_TEMPLATE_CONTACTS', '6e6f5a91-2cb9-4f42-bf26-0a13b2f1c101', 'ID de la plantilla de correu de tipus Notificació per a l''enviament de credencials de l''Àrea Privada a Persones.'),
('8a2014ed-569d-44ad-b03a-f39420aa7ef6', NOW(), NOW(), '1', '1', 0, '1', 'PRIVATEAREA', 'PRIVATEAREA_CREDENTIALS_TEMPLATE_ACCOUNTS', '6e6f5a91-2cb9-4f42-bf26-0a13b2f1c102', 'ID de la plantilla de correu de tipus Notificació per a l''enviament de credencials de l''Àrea Privada a Organitzacions.');