-- Notification templates for the job offers and job applications modules
REPLACE INTO email_templates (id,date_entered,date_modified,modified_user_id,created_by,published,name,description,subject,body,body_html,deleted,assigned_user_id,text_only,`type`) VALUES
	-- Job offer - Notification - Expired closing date and not closed status - Assigned user
    ('d3c1d5b7-f8d2-4df4-9f6b-2c63aa6b8e41', NOW(), NOW(), '1', '1', NULL, 'Example - Job offer with expired closing date without closed status (assigned user)', 'Notification to the assigned user that the offer has already expired and is not closed.', 'Job offer out of deadline:  $stic_job_offers_name', '$stic_job_offers_assigned_user_name:\r\n\r\nThe job offer $stic_job_offers_name has an expired application closing date and is currently in status $stic_job_offers_status.\r\n\r\nPlease review it and, if appropriate, update its status: $sugarurl/index.php?module=stic_Job_Offers&action=DetailView&record=$stic_job_offers_id', '<p>$stic_job_offers_assigned_user_name:</p>\n<p>The job offer <strong>$stic_job_offers_name</strong> has an expired application closing date and is currently in status <strong>$stic_job_offers_status</strong>.</p>\n<p><a href="$sugarurl/index.php?module=stic_Job_Offers&action=DetailView&record=$stic_job_offers_id">Review it</a> and, if appropriate, update its status.</p>', 0, '1', 0, 'notification'),
    -- Job offer - Notification - Expired closing date and not closed status - Interlocutor
    ('c2a9e9d1-1f5f-4c6c-9b3c-8d3c2a7f4b81', NOW(), NOW(), '1', '1', NULL, 'Example - Job offer with expired closing date without closed status (interlocutor)', 'Notification to the interlocutor that the offer has already expired and is not closed.', 'Job offer out of deadline: $stic_job_offers_name', 'Dear $contact_name:\r\n\r\nThe job offer $stic_job_offers_name has an expired application closing date and is currently in status $stic_job_offers_status.\r\n\r\nPlease review it and, if appropriate, update its status: $portal_address/?internalpage=single_stic_job_offers&action=detail&id=$stic_job_offers_id', '<p>Dear $contact_name:</p>\n<p>The job offer <strong>$stic_job_offers_name</strong> has an expired application closing date and is currently in status <strong>$stic_job_offers_status</strong>.</p>\n<p><a href="$portal_address/?internalpage=single_stic_job_offers&action=detail&id=$stic_job_offers_id">Review it</a> and, if appropriate, update its status.</p>', 0, '1', 0, 'notification'),
    -- Accepted application - Assigned user 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0001', NOW(), NOW(), '1', '1', NULL, 'Example - Application accepted (assigned user)', 'Notification to the assigned user when an application changes to Accepted.', 'Application accepted: $stic_job_applications_stic_job_applications_stic_job_offers_name', '$stic_job_applications_assigned_user_name:\r\n\r\nThe application of $stic_job_applications_stic_job_applications_contacts_name for the offer $stic_job_applications_stic_job_applications_stic_job_offers_name has been accepted.\r\n\r\nLink to the application: $sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id', '<p>$stic_job_applications_assigned_user_name:</p><p>The application of <strong>$stic_job_applications_stic_job_applications_contacts_name</strong> for the offer <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> has been <strong>accepted</strong>.</p><p><a href="$sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id">Link to the application</a>.</p>', 0, '1', 0, 'notification'),
    -- Accepted application - Candidate 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0002', NOW(), NOW(), '1', '1', NULL, 'Example - Application accepted (candidate)', 'Notification to the candidate when an application changes to Accepted.', 'Application accepted: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Dear $stic_job_applications_stic_job_applications_contacts_name:\r\n\r\nWe are pleased to inform you that your application for the offer $stic_job_applications_stic_job_applications_stic_job_offers_name has been accepted.\r\n\r\nLink to the application: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Dear $stic_job_applications_stic_job_applications_contacts_name:</p><p>We are pleased to inform you that your application for the offer <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> has been <strong>accepted</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id">Link to the application</a>.</p>', 0, '1', 0, 'notification'),
    -- Rejected or closed application - Assigned user 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0004', NOW(), NOW(), '1', '1', NULL, 'Example - Application rejected/closed (assigned user)', 'Notification to the assigned user when an application changes to Rejected or closed.', 'Application rejected or closed: $stic_job_applications_stic_job_applications_stic_job_offers_name', '$stic_job_applications_assigned_user_name:\n\nThe application of $stic_job_applications_stic_job_applications_contacts_name for the offer $stic_job_applications_stic_job_applications_stic_job_offers_name has been rejected.\r\n\r\nLink to the application: $sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id', '<p>$stic_job_applications_assigned_user_name:</p><p>The application of <strong>$stic_job_applications_stic_job_applications_contacts_name</strong> for the offer <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> has been rejected.</p><p><a href=\"$sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id\">Link to the application</a>.</p>', 0, '1', 0, 'notification'),
    -- Rejected or closed application - Candidate 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0005', NOW(), NOW(), '1', '1', NULL, 'Example - Application rejected/closed (candidate)', 'Notification to the candidate when an application changes to Rejected or closed.', 'Application rejected: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Dear $stic_job_applications_stic_job_applications_contacts_name:\n\nWe appreciate your interest in the offer $stic_job_applications_stic_job_applications_stic_job_offers_name.\n\nUnfortunately, on this occasion it has been decided to continue the process with other applications that more closely match the characteristics of the offer.\r\n\r\nLink to the application: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Dear $stic_job_applications_stic_job_applications_contacts_name:</p><p>We appreciate your interest in the offer <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong>.</p><p>Unfortunately, on this occasion it has been decided to continue the process with other applications that more closely match the characteristics of the offer.</p><p><a href=\"$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id\">Link to the application</a>.</p><p>We wish you great success. Sincerely, $stic_job_offers_stic_job_offers_accounts_name</p>', 0, '1', 0, 'notification'),
    -- Other application statuses - Assigned user 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0007', NOW(), NOW(), '1', '1', NULL, 'Example - Application other statuses (assigned user)', 'Notification to the assigned user when an application changes to Pending interview or Interviewed.', 'Application $stic_job_applications_status: $stic_job_applications_stic_job_applications_stic_job_offers_name', '$stic_job_applications_assigned_user_name:\r\n\r\nThe application of $stic_job_applications_stic_job_applications_contacts_name for the offer $stic_job_applications_stic_job_applications_stic_job_offers_name has changed to $stic_job_applications_status.\r\n\r\nLink to the application: $sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id', '<p>$stic_job_applications_assigned_user_name,</p><p>The application of <strong>$stic_job_applications_stic_job_applications_contacts_name</strong> for the offer <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> has changed to <strong>$stic_job_applications_status</strong>.</p><p><a href="$sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id">Link to the application</a>.</p>', 0, '1', 0, 'notification'),
    -- Other application statuses - Candidate 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0008', NOW(), NOW(), '1', '1', NULL, 'Example - Application other statuses (candidate)', 'Notification to the candidate when an application changes to Pending interview or Interviewed.', 'Application $stic_job_applications_status: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Dear $stic_job_applications_stic_job_applications_contacts_name:\r\n\r\nYour application for the offer $stic_job_applications_stic_job_applications_stic_job_offers_name has changed to $stic_job_applications_status.\r\n\r\nLink to the application: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Dear $stic_job_applications_stic_job_applications_contacts_name:</p><p>Your application for the offer <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> has changed to <strong>$stic_job_applications_status</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id">Link to the application</a>.</p>', 0, '1', 0, 'notification'),
    -- Offer - Status change - Assigned user 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0010', NOW(), NOW(), '1', '1', NULL, 'Example - Job offer status change (assigned user)', 'Notification to the assigned user on an offer status change.', 'Offer status change: $stic_job_offers_name', '$stic_job_offers_assigned_user_name:\r\n\r\nThe offer $stic_job_offers_name has changed to $stic_job_offers_status.\r\n\r\nLink to the offer: $sugarurl/index.php?module=stic_Job_Offers&action=DetailView&record=$stic_job_offers_id', '<p>$stic_job_offers_assigned_user_name:</p><p>The offer <strong>$stic_job_offers_name</strong> has changed to <strong>$stic_job_offers_status</strong>.</p><p><a href="$sugarurl/index.php?module=stic_Job_Offers&action=DetailView&record=$stic_job_offers_id">Link to the offer</a>.</p>', 0, '1', 0, 'notification'),
    -- Offer - Status change - Candidates 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0011', NOW(), NOW(), '1', '1', NULL, 'Example - Job offer status change (candidates)', 'Notification to the candidates on an offer status change.', 'Offer status change: $stic_job_offers_name', 'Dear:\r\n\r\nThe offer $stic_job_offers_name has changed to $stic_job_offers_status.\r\n\r\nLink to the offer: $portal_address/?internalpage=single_stic_job_offers&action=detail&id=$stic_job_offers_id', '<p>Dear:</p><p>The offer <strong>$stic_job_offers_name</strong> has changed to <strong>$stic_job_offers_status</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_offers&action=detail&id=$stic_job_offers_id">Link to the offer</a>.</p>', 0, '1', 0, 'notification'),
    -- Offer - Status change - Interlocutor 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0012', NOW(), NOW(), '1', '1', NULL, 'Example - Job offer status change (interlocutor)', 'Notification to the interlocutor on an offer status change.', 'Offer status change: $stic_job_offers_name', 'Dear $contact_name:\r\n\r\nThe offer $stic_job_offers_name has changed to $stic_job_offers_status.\r\n\r\nLink to the offer: $portal_address/?internalpage=single_stic_job_offers&action=detail&id=$stic_job_offers_id', '<p>Dear $contact_name:</p><p>The offer <strong>$stic_job_offers_name</strong> has changed to <strong>$stic_job_offers_status</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_offers&action=detail&id=$stic_job_offers_id">Link to the offer</a>.</p>', 0, '1', 0, 'notification'),
    -- Private Area - Access credentials - Contact
    ('6e6f5a91-2cb9-4f42-bf26-0a13b2f1c101', NOW(), NOW(), '1', '1', NULL, 'Example - Private area access credentials (contact)', 'Notification of private area access credentials when access is activated for a contact.', 'Your private area access credentials', '$contacts_name:\r\n\r\nYour access to the private area is already enabled.\r\n\r\nUsername: $contacts_stic_pa_username_c\r\nPassword: $contacts_stic_pa_password_c\r\n\r\nYou can access it at: $portal_address', '<p>$contacts_name:</p><p>Your access to the private area is already enabled.</p><p><strong>Username:</strong> $contacts_stic_pa_username_c<br><strong>Password:</strong> $contacts_stic_pa_password_c</p><p>You can access it at: <a href="$portal_address">$portal_address</a></p>', 0, '1', 0, 'notification'),
    -- Private Area - Access credentials - Account
    ('6e6f5a91-2cb9-4f42-bf26-0a13b2f1c102', NOW(), NOW(), '1', '1', NULL, 'Example - Private area access credentials (account)', 'Notification of private area access credentials when access is activated for an account.', 'Your private area access credentials', '$accounts_name:\r\n\r\nYour access to the private area is already enabled.\r\n\r\nUsername: $accounts_stic_pa_username_c\r\nPassword: $accounts_stic_pa_password_c\r\n\r\nYou can access it at: $portal_address\r\n\r\n', '<p>$accounts_name:</p><p>Your access to the private area is already enabled.</p><p><strong>Username:</strong> $accounts_stic_pa_username_c<br><strong>Password:</strong> $accounts_stic_pa_password_c</p><p>You can access it at: <a href="$portal_address">$portal_address</a></p>', 0, '1', 0, 'notification'),
    -- Jop applications - Notification - New application submitted
    ('7a9f8f3a-2d1f-4a40-9dd6-7c6f9e1b7001', NOW(), NOW(), '1', '1', NULL, 'Example - Application created (assigned user)', 'Notification to the assigned user when a new application is submitted.', 'New application received: $stic_job_applications_stic_job_applications_stic_job_offers_name', '$stic_job_applications_assigned_user_name:\r\n\r\n$stic_job_applications_stic_job_applications_contacts_name has submitted an application for the offer $stic_job_applications_stic_job_applications_stic_job_offers_name.\r\n\r\nLink to the application: $sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id', '<p>$stic_job_applications_assigned_user_name:</p><p><strong>$stic_job_applications_stic_job_applications_contacts_name</strong> has submitted an application for the offer <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong>.</p><p><a href=\"$sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id\">Link to the application</a>.</p>', 0, '1', 0, 'notification'),
    -- Job applications - Notification - Application registered (candidate)
    ('7a9f8f3a-2d1f-4a40-9dd6-7c6f9e1b7003', NOW(), NOW(), '1', '1', NULL, 'Example - Application created (candidate)', 'Notification to the candidate that the application has been registered.', 'Application received: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Dear $stic_job_applications_stic_job_applications_contacts_name:\r\n\r\nWe have received your application for the offer $stic_job_applications_stic_job_applications_stic_job_offers_name.\r\n\r\nLink to the application: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Dear $stic_job_applications_stic_job_applications_contacts_name:</p><p>We have received your application for the offer <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong>.</p><p><a href=\"$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id\">Link to the application</a>.</p>', 0, '1', 0, 'notification'),
    -- Message - Notification - New message in conversation
    ('7a9f8f3a-2d1f-4a40-9dd6-7c6f9e1b7002', NOW(), NOW(), '1', '1', NULL, 'Example - New message in conversation (assigned user)', 'Notification to the assigned user when a private area user sends a message in a conversation.', 'New message received', '$stic_messages_assigned_user_name:\r\n\r\nYou have received a message from a private area conversation.\r\n\r\nConversation:\r\n$stic_conversations_subject\r\n\r\nMessage:\r\n$stic_messages_message\r\n\r\nLink to the message: $sugarurl/index.php?module=stic_Messages&action=DetailView&record=$stic_messages_id', '<p>$stic_messages_assigned_user_name:</p><p>You have received a message from a private area conversation.</p><p><strong>Conversation:</strong><br>$stic_conversations_subject</p><p><strong>Message:</strong><br>$stic_messages_message</p><p><a href=\"$sugarurl/index.php?module=stic_Messages&action=DetailView&record=$stic_messages_id\">Link to the message</a>.</p>', 0, '1', 0, 'notification'),
    -- Job offers - Notification - New job offer (assigned user)
    ('3c0a5f6e-1111-4f8a-9a11-3b1b7c2a0101', NOW(), NOW(), '1', '1', NULL, 'Example - New job offer (assigned user)', 'Notification to the assigned user on a job offer creation.', 'Offer created: $stic_job_offers_name', '$stic_job_offers_assigned_user_name:\r\n\r\nA new job offer has been created: $stic_job_offers_name.\r\n\r\nLink to the offer: $sugarurl/index.php?module=stic_Job_Offers&action=DetailView&record=$stic_job_offers_id', '<p>$stic_job_offers_assigned_user_name:</p><p>A new job offer has been created: <strong>$stic_job_offers_name</strong>.</p><p><a href="$sugarurl/index.php?module=stic_Job_Offers&action=DetailView&record=$stic_job_offers_id">Link to the offer</a>.</p>', 0, '1', 0, 'notification'),
    -- Message - Notification - New message in conversation (contact)
    ('7a9f8f3a-2d1f-4a40-9dd6-7c6f9e1b7004', NOW(), NOW(), '1', '1', NULL, 'Example - New message in conversation (private area user)', 'Notification to the private area user when the assigned user sends a message in a conversation.', 'New message received', 'Dear $contact_name:\r\n\r\nYou have received a message in the private area.\r\n\r\nConversation:\r\n$stic_conversations_subject\r\n\r\nMessage:\r\n$stic_messages_message\r\n\r\nYou can view and reply to it in the private area: $portal_address/?internalpage=single_stic_chat&action=detail&id=$stic_conversations_id', '<p>Dear $contact_name:</p><p>You have received a message in the private area.</p><p><strong>Conversation:</strong><br>$stic_conversations_subject</p><p><strong>Message:</strong><br>$stic_messages_message</p><p>You can view and reply to it in the private area: <a href="$portal_address/?internalpage=single_stic_chat&action=detail&id=$stic_conversations_id">$portal_address</a>.</p>', 0, '1', 0, 'notification'),
    -- Job applications - Notification - Application presented (interlocutor)
    ('4f2c7b91-0c3e-4a2b-9b3e-7c4a9b1e9001', NOW(), NOW(), '1', '1', NULL, 'Example - Application submitted (interlocutor)', 'Notification to the interlocutor when an application changes to Submitted.', 'Application submitted: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Dear $contact_name:\r\n\r\n$stic_job_applications_stic_job_applications_contacts_name has submitted an application for the offer $stic_job_applications_stic_job_applications_stic_job_offers_name.\r\n\r\nLink to the application: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Dear $contact_name:</p><p><strong>$stic_job_applications_stic_job_applications_contacts_name</strong> has submitted an application for the offer <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id">Link to the application</a>.</p>', 0, '1', 0, 'notification'),
    -- Job applications - Notification - Application accepted (interlocutor)
    ('4f2c7b91-0c3e-4a2b-9b3e-7c4a9b1e9010', NOW(), NOW(), '1', '1', NULL, 'Example - Application accepted (interlocutor)', 'Notification to the interlocutor when an application changes to Accepted.', 'Application accepted: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Dear $contact_name:\r\n\r\nThe application of $stic_job_applications_stic_job_applications_contacts_name for the offer $stic_job_applications_stic_job_applications_stic_job_offers_name has been accepted.\r\n\r\nLink to the application: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Dear $contact_name:</p><p>The application of <strong>$stic_job_applications_stic_job_applications_contacts_name</strong> for the offer <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> has been <strong>accepted</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id">Link to the application</a>.</p>', 0, '1', 0, 'notification'),
    -- Job applications - Notification - Application rejected or closed (interlocutor)
    ('4f2c7b91-0c3e-4a2b-9b3e-7c4a9b1e9011', NOW(), NOW(), '1', '1', NULL, 'Example - Application rejected/closed (interlocutor)', 'Notification to the interlocutor when an application changes to Rejected or closed.', 'Application rejected or closed: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Dear $contact_name:\r\n\r\nThe application of $stic_job_applications_stic_job_applications_contacts_name for the offer $stic_job_applications_stic_job_applications_stic_job_offers_name has been rejected or closed.\r\n\r\nLink to the application: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Dear $contact_name:</p><p>The application of <strong>$stic_job_applications_stic_job_applications_contacts_name</strong> for the offer <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> has been <strong>rejected or closed</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id">Link to the application</a>.</p>', 0, '1', 0, 'notification'),
    -- Job applications - Notification - Application canceled (assigned user)
    ('4f2c7b91-0c3e-4a2b-9b3e-7c4a9b1e9002', NOW(), NOW(), '1', '1', NULL, 'Example - Application canceled (assigned user)', 'Notification to the assigned user when an application is canceled.', 'Application canceled: $stic_job_applications_stic_job_applications_stic_job_offers_name', '$stic_job_applications_assigned_user_name:\r\n\r\n$stic_job_applications_stic_job_applications_contacts_name has canceled the application for the offer $stic_job_applications_stic_job_applications_stic_job_offers_name.\r\n\r\nLink to the application: $sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id', '<p>$stic_job_applications_assigned_user_name:</p><p><strong>$stic_job_applications_stic_job_applications_contacts_name</strong> has canceled the application for the offer <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong>.</p><p><a href="$sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id">Link to the application</a>.</p>', 0, '1', 0, 'notification'),
    -- Job applications - Notification - Application canceled (interlocutor)
    ('4f2c7b91-0c3e-4a2b-9b3e-7c4a9b1e9003', NOW(), NOW(), '1', '1', NULL, 'Example - Application canceled (interlocutor)', 'Notification to the interlocutor when an application is canceled.', 'Application canceled: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Dear $contact_name:\r\n\r\n$stic_job_applications_stic_job_applications_contacts_name has canceled the application for the offer $stic_job_applications_stic_job_applications_stic_job_offers_name.\r\n\r\nLink to the application: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Dear $contact_name:</p><p><strong>$stic_job_applications_stic_job_applications_contacts_name</strong> has canceled the application for the offer <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id">Link to the application</a>.</p>', 0, '1', 0, 'notification');


-- Job offers - Notification - New job offer (assigned user)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('3c0a5f6e-0001-4f8a-9a11-3b1b7c2a0200', 'Job offers - Notification - New job offer (assigned user)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Workflow that sends a notification to assigned user when someone else creates a new job offer.', 0, '1', 'stic_Job_Offers', 'New_Records', 'Inactive', 'On_Save', 0, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('00000bd1-6280-6302-56a9-69fb0de58e31', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3c0a5f6e-0001-4f8a-9a11-3b1b7c2a0200', 1, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'assigned_user_name', 'Not_Equal_To', 'Field', 'created_by_name');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('3c0a5f6e-0001-4f8a-9a11-3b1b7c2a0201', 'Send notification (assigned user)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3c0a5f6e-0001-4f8a-9a11-3b1b7c2a0200', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiM2MwYTVmNmUtMTExMS00ZjhhLTlhMTEtM2IxYjdjMmEwMTAxIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxODoiYXNzaWduZWRfdXNlcl9saW5rIjt9fQ==');

-- Job offers - Notification - Expired closing date and not closed status (assigned user)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('000009c0-3302-dbf2-c1b7-69a850a8b6d5', 'Job offers - Notification - Closing date (assigned user)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Workflow that sends a notification to the assigned user when a job offer closing date is yesterday and status is not Closed.', 0, '1', 'stic_Job_Offers', 'All_Records', 'Inactive', 'In_Scheduler', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('000000cd-0341-b540-66b5-69a8502ff15d', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000009c0-3302-dbf2-c1b7-69a850a8b6d5', 3, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'assigned_user_name', 'Not_Equal_To', 'Value', NULL),
('000002a2-0646-1de2-e72c-69a85088e3cf', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000009c0-3302-dbf2-c1b7-69a850a8b6d5', 1, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'applications_end_date', 'Equal_To', 'Date', 'YTo0OntpOjA7czo1OiJ0b2RheSI7aToxO3M6NToibWludXMiO2k6MjtzOjE6IjEiO2k6MztzOjM6ImRheSI7fQ=='),
('000003b5-2bb2-8999-84b6-69a850918ce2', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000009c0-3302-dbf2-c1b7-69a850a8b6d5', 2, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'status', 'Not_Equal_To', 'Multi', '^closed_covered^,^closed_partially_covered^,^closed_not_covered^');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000727-a7fd-96e4-64fa-69a850c229f5', 'Send notification (assigned user)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000009c0-3302-dbf2-c1b7-69a850a8b6d5', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIwIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiZDNjMWQ1YjctZjhkMi00ZGY0LTlmNmItMmM2M2FhNmI4ZTQxIjtzOjEzOiJvdXRib3VuZF9zbXRwIjtzOjY6InN5c3RlbSI7czoxNToiZnJvbV9lbWFpbF9uYW1lIjtzOjA6IiI7czoxODoiZnJvbV9lbWFpbF9hZGRyZXNzIjtzOjA6IiI7czoxMzoicmVwbHlfdG9fbmFtZSI7czowOiIiO3M6ODoicmVwbHlfdG8iO3M6MDoiIjtzOjEzOiJlbWFpbF90b190eXBlIjthOjE6e2k6MDtzOjI6InRvIjt9czoxNzoiZW1haWxfdGFyZ2V0X3R5cGUiO2E6MTp7aTowO3M6MTM6IlJlbGF0ZWQgRmllbGQiO31zOjU6ImVtYWlsIjthOjE6e2k6MDtzOjE4OiJhc3NpZ25lZF91c2VyX2xpbmsiO319');

-- Job offers - Notification - Expired closing date and not closed status (interlocutor)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000815-c8ac-f000-0454-69fb1eb45882', 'Job offers - Notification - Closing date (interlocutor)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Workflow that sends a notification to the interlocutor when a job offer closing date is yesterday and status is not Closed.', 0, '1', 'stic_Job_Offers', 'All_Records', 'Inactive', 'In_Scheduler', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('000002f1-b9de-d1e8-df06-69fb1eaaa748', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000815-c8ac-f000-0454-69fb1eb45882', 1, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'applications_end_date', 'Equal_To', 'Date', 'YTo0OntpOjA7czo1OiJ0b2RheSI7aToxO3M6NToibWludXMiO2k6MjtzOjE6IjEiO2k6MztzOjM6ImRheSI7fQ=='),
('00000a88-3ede-584f-ae0e-69fb1eed8a19', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000815-c8ac-f000-0454-69fb1eb45882', 3, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'interlocutor', 'Not_Equal_To', 'Value', NULL),
('00000cec-1ccd-0c68-a46d-69fb1e96bc1c', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000815-c8ac-f000-0454-69fb1eb45882', 2, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'status', 'Not_Equal_To', 'Multi', '^closed_covered^,^closed_partially_covered^,^closed_not_covered^');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000338-84ca-31fe-96f1-69fb1e28a9db', 'Send notification (interlocutor)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000815-c8ac-f000-0454-69fb1eb45882', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIwIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiYzJhOWU5ZDEtMWY1Zi00YzZjLTliM2MtOGQzYzJhN2Y0YjgxIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxMjoiaW50ZXJsb2N1dG9yIjt9fQ==');

-- Job applications - Notification - New application (assigned user / candidate)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a101', 'Job applications - Notification - New application (assigned user / candidate)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Workflow that sends a notification to the assigned user when someone else (a potential candidate or another CRM user) creates an application. The candidate also gets a confirmation.', 0, '1', 'stic_Job_Applications', 'New_Records', 'Inactive', 'On_Save', 0, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('0000043a-c7f6-133c-4b52-69fb5600df06', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a101', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'created_by_name', 'Not_Equal_To', 'Field', 'assigned_user_name'),
('0000047a-f4b7-3937-dff0-69d8c03ca9bd', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a101', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'review');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a103', 'Send notification (assigned user)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a101', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiN2E5ZjhmM2EtMmQxZi00YTQwLTlkZDYtN2M2ZjllMWI3MDAxIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxODoiYXNzaWduZWRfdXNlcl9saW5rIjt9fQ=='),
('2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a104', 'Send notification (candidate)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a101', 2, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiN2E5ZjhmM2EtMmQxZi00YTQwLTlkZDYtN2M2ZjllMWI3MDAzIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MzA6InN0aWNfam9iX2FwcGxpY2F0aW9uc19jb250YWN0cyI7fX0=');

-- Job applications - Notification - New application (candidate)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('000006a9-afb9-d96f-0c92-69fb56113842', 'Job applications - Notification - New application (candidate)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Workflow that sends a notification to the candidate when an application is created by the assigned user on his behalf.', 0, '1', 'stic_Job_Applications', 'New_Records', 'Inactive', 'On_Save', 0, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('0000074b-8f66-a4cf-721f-69fb56d5b469', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000006a9-afb9-d96f-0c92-69fb56113842', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'created_by_name', 'Equal_To', 'Field', 'assigned_user_name'),
('0000095f-fb16-acd0-9a04-69fb56f0038e', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000006a9-afb9-d96f-0c92-69fb56113842', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'review');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000958-87e6-f511-43f9-69fb56e5893a', 'Send notification (candidate)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000006a9-afb9-d96f-0c92-69fb56113842', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiN2E5ZjhmM2EtMmQxZi00YTQwLTlkZDYtN2M2ZjllMWI3MDAzIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czozMDoic3RpY19qb2JfYXBwbGljYXRpb25zX2NvbnRhY3RzIjt9fQ==');

-- Job applications - Notification - Presented (candidate)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000f20-7b3a-4a1b-8f2a-69a830ec33d0', 'Job applications - Notification - Presented status (candidate)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Workflow that sends a notification to the candidate when an application changes to Presented status.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('00000f21-7b3a-4a1b-8f2a-69a830ec33d0', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000f20-7b3a-4a1b-8f2a-69a830ec33d0', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'presented'),
('00000f22-7b3a-4a1b-8f2a-69a830ec33d0', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000f20-7b3a-4a1b-8f2a-69a830ec33d0', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL);
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000f23-7b3a-4a1b-8f2a-69a830ec33d0', 'Send notification (candidate)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000f20-7b3a-4a1b-8f2a-69a830ec33d0', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA4IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MzA6InN0aWNfam9iX2FwcGxpY2F0aW9uc19jb250YWN0cyI7fX0=');

-- Job applications - Notification - Accepted (assigned user / candidate)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000190-75e4-3e38-5f8f-69a82fb83c15', 'Job applications - Notification - Accepted (assigned user / candidate)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Workflow that sends a notification to the assigned user and the candidate when someone else (the interlocutor or another CRM user) changes an application to Accepted.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('000003b6-1b3f-4bc3-b4f5-69a82f8345f3', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000190-75e4-3e38-5f8f-69a82fb83c15', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'accepted'),
('00000778-cf26-a3ea-ab3c-69fb592f7d71', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000190-75e4-3e38-5f8f-69a82fb83c15', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Not_Equal_To', 'Field', 'assigned_user_name'),
('00000f10-1111-2222-3333-69a82fb83c15', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000190-75e4-3e38-5f8f-69a82fb83c15', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL);
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('000009bf-d247-6e61-ac71-69a82f5103df', 'Send notification (assigned user)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000190-75e4-3e38-5f8f-69a82fb83c15', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDAxIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MTg6ImFzc2lnbmVkX3VzZXJfbGluayI7fX0='),
('000009c1-d247-6e61-ac71-69a82f5103d1', 'Send notification (candidate)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000190-75e4-3e38-5f8f-69a82fb83c15', 2, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDAyIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MzA6InN0aWNfam9iX2FwcGxpY2F0aW9uc19jb250YWN0cyI7fX0=');

-- Job applications - Notification - Accepted (candidate)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000101-4d1c-b7e4-7fc4-69fb5af86cfa', 'Job applications - Notification - Accepted (candidate)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Workflow that sends a notification to the candidate when the assigned user changed the application to Accepted.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('0000054f-feaa-42b0-ba34-69fb5a7a4d76', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000101-4d1c-b7e4-7fc4-69fb5af86cfa', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Equal_To', 'Field', 'assigned_user_name'),
('00000876-3720-e155-6d3a-69fb5aaf478a', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000101-4d1c-b7e4-7fc4-69fb5af86cfa', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL),
('00000b3c-676c-7b20-3da5-69fb5abe6397', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000101-4d1c-b7e4-7fc4-69fb5af86cfa', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'accepted');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('000007cf-9d70-dd55-61c1-69fb5adc6f5b', 'Send notification (candidate)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000101-4d1c-b7e4-7fc4-69fb5af86cfa', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDAyIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czozMDoic3RpY19qb2JfYXBwbGljYXRpb25zX2NvbnRhY3RzIjt9fQ==');

-- Job applications - Notification - Rejected or closed (assigned user / candidate)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000ace-02d2-2425-107e-69a82a9eacb5', 'Job applications - Notification - Rejected or closed (assigned user / candidate)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Workflow that sends a notification to the candidate and the assigned user when someone else (the interlocutor or another CRM user) changes an application to Rejected or closed.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('000001a5-41d3-7d65-fe58-69a82a22be9d', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'rejected_closed'),
('00000bb2-129d-3cff-4d79-69fb5a5c974d', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 4, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Not_Equal_To', 'Field', 'assigned_user_name'),
('00000f11-1111-2222-3333-69a82a9eacb5', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL),
('00000f14-7b3a-4a1b-8f2a-69a82a9eacb6', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'rejection_reason', 'Not_Equal_To', 'Value', 'resignation');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000b52-cd9a-161e-c7d1-69a82a27d7fb', 'Send notification (assigned user)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA0IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MTg6ImFzc2lnbmVkX3VzZXJfbGluayI7fX0='),
('00000b53-cd9a-161e-c7d1-69a82a27d7f1', 'Send notification (candidate)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 2, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA1IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MzA6InN0aWNfam9iX2FwcGxpY2F0aW9uc19jb250YWN0cyI7fX0=');

-- Job applications - Notification - Rejected or closed (candidate)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('000001be-e27b-e9a6-98aa-69fb5a33138a', 'Job applications - Notification - Rejected or closed (candidate)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Workflow that sends a notification to the candidate when the assigned user changes an application to Rejected or closed.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('00000181-a6bf-cbe4-a82a-69fb5ae259c6', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000001be-e27b-e9a6-98aa-69fb5a33138a', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL),
('00000214-51dc-4a76-e116-69fb5a064799', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000001be-e27b-e9a6-98aa-69fb5a33138a', 4, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Equal_To', 'Field', 'assigned_user_name'),
('00000849-bf4b-beca-85d7-69fb5a80dc0e', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000001be-e27b-e9a6-98aa-69fb5a33138a', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'rejection_reason', 'Not_Equal_To', 'Value', 'resignation'),
('000009d7-2129-6ea1-ff80-69fb5acbdca7', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000001be-e27b-e9a6-98aa-69fb5a33138a', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'rejected_closed');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('0000085b-5ed1-39bc-6fc1-69fb5a995e7a', 'Send notification (candidate)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000001be-e27b-e9a6-98aa-69fb5a33138a', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA1IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czozMDoic3RpY19qb2JfYXBwbGljYXRpb25zX2NvbnRhY3RzIjt9fQ==');

-- Job applications - Notification - Other statuses (assigned user / candidate)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000174-497a-ef41-5ae8-69a830ec33ce', 'Job applications - Notification - Other statuses (Changed by Interlocutor)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Workflow that sends a notification to the assigned user and the candidate when someone else (the interlocutor or another CRM user) changes an application to the status Pending interview or Interviewed.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('0000033d-8ae0-fe4a-64ba-69a830439caf', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000174-497a-ef41-5ae8-69a830ec33ce', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Multi', '^pending_interview^,^interviewed^'),
('00000603-e27d-aab5-227a-69fb24be4977', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000174-497a-ef41-5ae8-69a830ec33ce', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Not_Equal_To', 'Field', 'assigned_user_name'),
('00000f12-1111-2222-3333-69a830ec33ce', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000174-497a-ef41-5ae8-69a830ec33ce', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL);
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000b79-f2fc-034b-4bb2-69a830fb223b', 'Send notification (assigned user)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000174-497a-ef41-5ae8-69a830ec33ce', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA3IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxODoiYXNzaWduZWRfdXNlcl9saW5rIjt9fQ=='),
('00000b80-f2fc-034b-4bb2-69a830fb2240', 'Send notification (candidate)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000174-497a-ef41-5ae8-69a830ec33ce', 2, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA4IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czozMDoic3RpY19qb2JfYXBwbGljYXRpb25zX2NvbnRhY3RzIjt9fQ==');

-- Job applications - Notification - Other statuses (candidate)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('000003e0-ebe2-ff1f-40d2-69fb278f5ab6', 'Job applications - Notification - Other statuses (candidate)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Workflow that sends a notification to the candidate when the assigned user changes an application to the status Pending interview or Interviewed.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('00000026-e7ad-3c88-57b0-69fb27298480', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000003e0-ebe2-ff1f-40d2-69fb278f5ab6', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Equal_To', 'Field', 'assigned_user_name'),
('0000019e-3313-a824-8459-69fb275e68a5', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000003e0-ebe2-ff1f-40d2-69fb278f5ab6', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL),
('00000bcb-699f-9731-d947-69fb27e8ef59', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000003e0-ebe2-ff1f-40d2-69fb278f5ab6', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Multi', '^pending_interview^,^interviewed^');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000225-589a-fac8-0b73-69fb275b376d', 'Send notification (candidate)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000003e0-ebe2-ff1f-40d2-69fb278f5ab6', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA4IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czozMDoic3RpY19qb2JfYXBwbGljYXRpb25zX2NvbnRhY3RzIjt9fQ==');

-- Messages - Notification - New message (assigned user)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b201', 'Messages - Notification - New message', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Workflow that sends a notification to the assigned user when a new message is received in conversations.', 0, '1', 'stic_Messages', 'New_Records', 'Inactive', 'On_Save', 0, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b202', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b201', 1, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'type', 'Equal_To', 'Value', 'private_area'),
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b203', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b201', 2, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'status', 'Equal_To', 'Value', 'sent'),
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b204', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b201', 3, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'parent_type', 'Equal_To', 'Value', 'Contacts');
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b206', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b201', 4, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'direction', 'Equal_To', 'Value', 'inbound');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b205', 'Send notification (assigned user)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b201', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiN2E5ZjhmM2EtMmQxZi00YTQwLTlkZDYtN2M2ZjllMWI3MDAyIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxODoiYXNzaWduZWRfdXNlcl9saW5rIjt9fQ==');

-- Messages - Notification - New message (private area user)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b210', 'Messages - Notification - New message (private area user)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Workflow that sends a notification to the related contact when the assigned user sends a new message in conversations.', 0, '1', 'stic_Messages', 'New_Records', 'Inactive', 'On_Save', 0, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b212', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b210', 1, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'type', 'Equal_To', 'Value', 'private_area'),
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b213', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b210', 2, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'status', 'Equal_To', 'Value', 'sent'),
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b214', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b210', 3, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'parent_type', 'Equal_To', 'Value', 'Contacts'),
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b215', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b210', 4, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'direction', 'Equal_To', 'Value', 'outbound');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b211', 'Send notification (private area user)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b210', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiN2E5ZjhmM2EtMmQxZi00YTQwLTlkZDYtN2M2ZjllMWI3MDA0IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxOToicGFyZW50X2NvbnRhY3RfbmFtZSI7fX0=');

-- Setting for sending Private Area credentials email
REPLACE INTO `stic_settings` (`id`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `deleted`, `assigned_user_id`, `type`, `name`, `value`, `description`) VALUES
('f8b4a3a2-9f40-4c2e-9f8d-5e76a20f5d11', NOW(), NOW(), '1', '1', 0, '1', 'PRIVATEAREA', 'PRIVATEAREA_SEND_CREDENTIALS_ON_ENABLE', '0', 'Indicates whether the Private Area credentials will be automatically sent when checking the "Activate Private Area" field in Contacts and Accounts modules (0 = No (default value), 1 = Yes).'),
('4ef9497d-6511-4a87-9467-01ca8ac99f20', NOW(), NOW(), '1', '1', 0, '1', 'PRIVATEAREA', 'PRIVATEAREA_CREDENTIALS_TEMPLATE_CONTACTS', '6e6f5a91-2cb9-4f42-bf26-0a13b2f1c101', 'Notification email template ID used to send Private Area credentials for Contacts'),
('8a2014ed-569d-44ad-b03a-f39420aa7ef6', NOW(), NOW(), '1', '1', 0, '1', 'PRIVATEAREA', 'PRIVATEAREA_CREDENTIALS_TEMPLATE_ACCOUNTS', '6e6f5a91-2cb9-4f42-bf26-0a13b2f1c102', 'Notification email template ID used to send Private Area credentials for Accounts');
