-- Plantillas de notificaciones para el módulo de ofertas laborales y candidaturas
REPLACE INTO email_templates (id,date_entered,date_modified,modified_user_id,created_by,published,name,description,subject,body,body_html,deleted,assigned_user_id,text_only,`type`) VALUES
	 -- Oferta laboral - Notificación - Cierre vencido y estado no cerrado - Usuario asignado
	('d3c1d5b7-f8d2-4df4-9f6b-2c63aa6b8e41', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Oferta laboral con cierre vencido sin estado cerrada (usuario asignado)', 'Notificación al usuario asignado que la oferta ya ha caducado y no está cerrada.', 'Oferta laboral fuera de plazo:  $stic_job_offers_name', '$stic_job_offers_assigned_user_name:\r\n\r\nLa oferta laboral $stic_job_offers_name tiene la fecha de cierre de candidaturas vencida y actualmente está en estado $stic_job_offers_status.\r\n\r\nRevísela y, si procede, actualice su estado: $sugarurl/index.php?module=stic_Job_Offers&action=DetailView&record=$stic_job_offers_id', '<p>$stic_job_offers_assigned_user_name:</p>\n<p>La oferta laboral <strong>$stic_job_offers_name</strong> tiene la fecha de cierre de candidaturas vencida y actualmente está en estado <strong>$stic_job_offers_status</strong>.</p>\n<p><a href="$sugarurl/index.php?module=stic_Job_Offers&action=DetailView&record=$stic_job_offers_id">Revísela</a> y, si procede, actualice su estado.</p>', 0, '1', 0, 'notification'),
    -- Oferta laboral - Notificación - Cierre vencido y estado no cerrado - Interlocutor
    ('c2a9e9d1-1f5f-4c6c-9b3c-8d3c2a7f4b81', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Oferta laboral con cierre vencido sin estado cerrada (interlocutor)', 'Notificación al interlocutor que la oferta ya ha caducado y no está cerrada.', 'Oferta laboral fuera de plazo: $stic_job_offers_name', 'Apreciado/a $contact_name:\r\n\r\nLa oferta laboral $stic_job_offers_name tiene la fecha de cierre de candidaturas vencida y actualmente está en estado $stic_job_offers_status.\r\n\r\nRevísela y, si procede, actualice su estado: $portal_address/?internalpage=single_stic_job_offers&action=detail&id=$stic_job_offers_id', '<p>Apreciado/a $contact_name:</p>\n<p>La oferta laboral <strong>$stic_job_offers_name</strong> tiene la fecha de cierre de candidaturas vencida y actualmente está en estado <strong>$stic_job_offers_status</strong>.</p>\n<p><a href="$portal_address/?internalpage=single_stic_job_offers&action=detail&id=$stic_job_offers_id">Revísela</a> y, si procede, actualice su estado.</p>', 0, '1', 0, 'notification'),
    -- Candidatura Aceptada - Usuario asignado 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0001', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Candidatura aceptada (usuario asignado)', 'Notificación al usuario asignado cuando una candidatura pasa a Aceptada.', 'Candidatura aceptada: $stic_job_applications_stic_job_applications_stic_job_offers_name', '$stic_job_applications_assigned_user_name:\r\n\r\nLa candidatura de $stic_job_applications_stic_job_applications_contacts_name para la oferta $stic_job_applications_stic_job_applications_stic_job_offers_name ha sido aceptada.\r\n\r\nEnlace a la candidatura: $sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id', '<p>$stic_job_applications_assigned_user_name:</p><p>La candidatura de <strong>$stic_job_applications_stic_job_applications_contacts_name</strong> para la oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> ha sido <strong>aceptada</strong>.</p><p><a href="$sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id">Enlace a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Candidatura Aceptada - Candidato 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0002', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Candidatura aceptada (candidato)', 'Notificación al candidato cuando una candidatura pasa a Aceptada.', 'Candidatura aceptada: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Apreciado/a $stic_job_applications_stic_job_applications_contacts_name:\r\n\r\nNos complace informarle que su candidatura para la oferta $stic_job_applications_stic_job_applications_stic_job_offers_name ha sido aceptada.\r\n\r\nEnlace a la candidatura: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Apreciado/a $stic_job_applications_stic_job_applications_contacts_name:</p><p>Nos complace informarle que su candidatura para la oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> ha sido <strong>aceptada</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id">Enlace a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Candidatura Rechazada o cerrada - Usuario asignado 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0004', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Candidatura rechazada/cerrada (usuario asignado)', 'Notificación al usuario asignado cuando una candidatura pasa a Rechazada o cerrada.', 'Candidatura rechazada o cerrada: $stic_job_applications_stic_job_applications_stic_job_offers_name', '$stic_job_applications_assigned_user_name:\n\nLa candidatura de $stic_job_applications_stic_job_applications_contacts_name para la oferta $stic_job_applications_stic_job_applications_stic_job_offers_name ha sido rechazada.\r\n\r\nEnlace a la candidatura: $sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id', '<p>$stic_job_applications_assigned_user_name:</p><p>La candidatura de <strong>$stic_job_applications_stic_job_applications_contacts_name</strong> para la oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> ha sido rechazada.</p><p><a href=\"$sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id\">Enlace a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Candidatura Rechazada o cerrada - Candidato 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0005', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Candidatura rechazada/cerrada (candidato)', 'Notificación al candidato cuando una candidatura pasa a Rechazada o cerrada.', 'Candidatura rechazada: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Apreciado/a $stic_job_applications_stic_job_applications_contacts_name:\n\nLe agradecemos el interés en la oferta de $stic_job_applications_stic_job_applications_stic_job_offers_name.\n\nLamentablemente, en esta ocasión se ha decidido continuar el proceso con otras candidaturas que se ajustan más a las características de la oferta.\r\n\r\nEnlace a la candidatura: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Apreciado/a $stic_job_applications_stic_job_applications_contacts_name:</p><p>Le agradecemos el interés en la oferta de <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong>.</p><p>Lamentablemente, en esta ocasión se ha decidido continuar el proceso con otras candidaturas que se ajustan más a las características de la oferta.</p><p><a href=\"$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id\">Enlace a la candidatura</a>.</p><p>Le deseamos mucho éxito. Atentamente, $stic_job_offers_stic_job_offers_accounts_name</p>', 0, '1', 0, 'notification'),
    -- Candidatura Otros estados - Usuario asignado 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0007', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Candidatura otros estados (usuario asignado)', 'Notificación al usuario asignado cuando una candidatura pasa a Pendiente de entrevista o Entrevistada.', 'Candidatura $stic_job_applications_status: $stic_job_applications_stic_job_applications_stic_job_offers_name', '$stic_job_applications_assigned_user_name:\r\n\r\nLa candidatura de $stic_job_applications_stic_job_applications_contacts_name para la oferta $stic_job_applications_stic_job_applications_stic_job_offers_name ha cambiado a $stic_job_applications_status.\r\n\r\nEnlace a la candidatura: $sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id', '<p>$stic_job_applications_assigned_user_name,</p><p>La candidatura de <strong>$stic_job_applications_stic_job_applications_contacts_name</strong> para la oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> ha cambiado a <strong>$stic_job_applications_status</strong>.</p><p><a href="$sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id">Enlace a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Candidatura Otros estados - Candidato 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0008', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Candidatura otros estados (candidato)', 'Notificación al candidato cuando una candidatura pasa a Pendiente de entrevista o Entrevistada.', 'Candidatura $stic_job_applications_status: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Apreciado/a $stic_job_applications_stic_job_applications_contacts_name:\r\n\r\nSu candidatura para la oferta $stic_job_applications_stic_job_applications_stic_job_offers_name ha cambiado a $stic_job_applications_status.\r\n\r\nEnlace a la candidatura: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Apreciado/a $stic_job_applications_stic_job_applications_contacts_name:</p><p>Su candidatura para la oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> ha cambiado a <strong>$stic_job_applications_status</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id">Enlace a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Oferta - Cambio de estado - Usuario asignado 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0010', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Cambio de estado de oferta laboral (usuario asignado)', 'Notificación al usuario asignado del cambio de estado de una oferta.', 'Cambio de estado de la oferta: $stic_job_offers_name', '$stic_job_offers_assigned_user_name:\r\n\r\nLa oferta $stic_job_offers_name ha cambiado a $stic_job_offers_status.\r\n\r\nEnlace a la oferta: $sugarurl/index.php?module=stic_Job_Offers&action=DetailView&record=$stic_job_offers_id', '<p>$stic_job_offers_assigned_user_name:</p><p>La oferta <strong>$stic_job_offers_name</strong> ha cambiado a <strong>$stic_job_offers_status</strong>.</p><p><a href="$sugarurl/index.php?module=stic_Job_Offers&action=DetailView&record=$stic_job_offers_id">Enlace a la oferta</a>.</p>', 0, '1', 0, 'notification'),
    -- Oferta - Cambio de estado - Candidatos 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0011', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Cambio de estado de oferta laboral (candidatos)', 'Notificación a los candidatos del cambio de estado de una oferta.', 'Cambio de estado de la oferta: $stic_job_offers_name', 'Apreciado/a:\r\n\r\nLa oferta $stic_job_offers_name ha cambiado a $stic_job_offers_status.\r\n\r\nEnlace a la oferta: $portal_address/?internalpage=single_stic_job_offers&action=detail&id=$stic_job_offers_id', '<p>Apreciado/a:</p><p>La oferta <strong>$stic_job_offers_name</strong> ha cambiado a <strong>$stic_job_offers_status</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_offers&action=detail&id=$stic_job_offers_id">Enlace a la oferta</a>.</p>', 0, '1', 0, 'notification'),
    -- Oferta - Cambio de estado - Interlocutor 
    ('1a2d6f10-8e32-4f8a-9a11-3b1b7c2a0012', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Cambio de estado de oferta laboral (interlocutor)', 'Notificación al interlocutor del cambio de estado de una oferta.', 'Actualización de la oferta: $stic_job_offers_name', 'Apreciado/a $contact_name:\r\n\r\nLa oferta $stic_job_offers_name ha cambiado a $stic_job_offers_status.\r\n\r\nEnlace a la oferta: $portal_address/?internalpage=single_stic_job_offers&action=detail&id=$stic_job_offers_id', '<p>Apreciado/a $contact_name:</p><p>La oferta <strong>$stic_job_offers_name</strong> ha cambiado a <strong>$stic_job_offers_status</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_offers&action=detail&id=$stic_job_offers_id">Enlace a la oferta</a>.</p>', 0, '1', 0, 'notification'),
    -- Área Privada - Credenciales de acceso - Persona
    ('6e6f5a91-2cb9-4f42-bf26-0a13b2f1c101', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Credenciales de acceso al área privada (persona)', 'Notificación de las credenciales de acceso al área privada cuando se activa el acceso de una persona.', 'Sus credenciales de acceso al área privada', '$contacts_name:\r\n\r\nYa tiene habilitado el acceso al área privada.\r\n\r\nUsuario: $contacts_stic_pa_username_c\r\nContraseña: $contacts_stic_pa_password_c\r\n\r\nPuede acceder en la dirección: $portal_address', '<p>$contacts_name:</p><p>Ya tiene habilitado el acceso al área privada.</p><p><strong>Usuario:</strong> $contacts_stic_pa_username_c<br><strong>Contraseña:</strong> $contacts_stic_pa_password_c</p><p>Puede acceder en la dirección: <a href="$portal_address">$portal_address</a></p>', 0, '1', 0, 'notification'),
    -- Área Privada - Credenciales de acceso - Organización
    ('6e6f5a91-2cb9-4f42-bf26-0a13b2f1c102', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Credenciales de acceso al área privada (organización)', 'Notificación de las credenciales de acceso al área privada cuando se activa el acceso de una organización.', 'Sus credenciales de acceso al área privada', '$accounts_name:\r\n\r\nYa tiene habilitado el acceso al área privada.\r\n\r\nUsuario: $accounts_stic_pa_username_c\r\nContraseña: $accounts_stic_pa_password_c\r\n\r\nPuede acceder en la dirección: $portal_address\r\n\r\n', '<p>$accounts_name:</p><p>Ya tiene habilitado el acceso al área privada.</p><p><strong>Usuario:</strong> $accounts_stic_pa_username_c<br><strong>Contraseña:</strong> $accounts_stic_pa_password_c</p><p>Puede acceder en la dirección: <a href="$portal_address">$portal_address</a></p>', 0, '1', 0, 'notification'),
    -- Candidatura - Noficación - Nueva candidatura presentada (Usuario asignado)
    ('7a9f8f3a-2d1f-4a40-9dd6-7c6f9e1b7001', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Candidatura creada (usuario asignado)', 'Notificación al usuario asignado cuando se crea una nueva candidatura.', 'Nueva candidatura recibida: $stic_job_applications_stic_job_applications_stic_job_offers_name', '$stic_job_applications_assigned_user_name:\r\n\r\n$stic_job_applications_stic_job_applications_contacts_name ha presentado su candidatura a la oferta $stic_job_applications_stic_job_applications_stic_job_offers_name.\r\n\r\nEnlace a la candidatura: $sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id', '<p>$stic_job_applications_assigned_user_name:</p><p><strong>$stic_job_applications_stic_job_applications_contacts_name</strong> ha presentado su candidatura a la oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong>.</p><p><a href=\"$sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id\">Enlace a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Candidatura - Notificación - Candidatura registrada (candidato)
    ('7a9f8f3a-2d1f-4a40-9dd6-7c6f9e1b7003', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Candidatura creada (candidato)', 'Notificación al candidato que su candidatura ha sido registrada.', 'Candidatura recibida: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Apreciado/a $stic_job_applications_stic_job_applications_contacts_name:\r\n\r\nHemos recibido su candidatura para la oferta $stic_job_applications_stic_job_applications_stic_job_offers_name.\r\n\r\nEnlace a la candidatura: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Apreciado/a $stic_job_applications_stic_job_applications_contacts_name:</p><p>Hemos recibido su candidatura para la oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong>.</p><p><a href=\"$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id\">Enlace a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Mensaje - Notificación - Nuevo mensaje en conversación
    ('7a9f8f3a-2d1f-4a40-9dd6-7c6f9e1b7002', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Nuevo mensaje en conversación (usuario asignado)', 'Notificación al usuario asignado cuando un usuario del área privada emite un mensaje en una conversación.', 'Nuevo mensaje recibido', '$stic_messages_assigned_user_name:\r\n\r\nHa recibido un mensaje de una conversación del área privada.\r\n\r\nConversación:\r\n$stic_conversations_subject\r\n\r\nMensaje:\r\n$stic_messages_message\r\n\r\nEnlace al mensaje: $sugarurl/index.php?module=stic_Messages&action=DetailView&record=$stic_messages_id', '<p>$stic_messages_assigned_user_name:</p><p>Ha recibido un mensaje de una conversación del área privada.</p><p><strong>Conversación:</strong><br>$stic_conversations_subject</p><p><strong>Mensaje:</strong><br>$stic_messages_message</p><p><a href=\"$sugarurl/index.php?module=stic_Messages&action=DetailView&record=$stic_messages_id\">Enlace al mensaje</a>.</p>', 0, '1', 0, 'notification'),
    -- Ofertas laborales - Notificación - Nueva oferta laboral (usuario asignado)
    ('3c0a5f6e-1111-4f8a-9a11-3b1b7c2a0101', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Nueva oferta laboral (usuario asignado)', 'Notificación al usuario asignado de la creación de una oferta laboral.', 'Oferta creada: $stic_job_offers_name', '$stic_job_offers_assigned_user_name:\r\n\r\nSe ha creado una nueva oferta laboral: $stic_job_offers_name.\r\n\r\nEnlace a la oferta: $sugarurl/index.php?module=stic_Job_Offers&action=DetailView&record=$stic_job_offers_id', '<p>$stic_job_offers_assigned_user_name:</p><p>Se ha creado una nueva oferta laboral: <strong>$stic_job_offers_name</strong>.</p><p><a href="$sugarurl/index.php?module=stic_Job_Offers&action=DetailView&record=$stic_job_offers_id">Enlace a la oferta</a>.</p>', 0, '1', 0, 'notification'),
    -- Mensaje - Notificación - Nuevo mensaje en conversación (persona relacionada)
    ('7a9f8f3a-2d1f-4a40-9dd6-7c6f9e1b7004', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Nuevo mensaje en conversación (usuario del área privada)', 'Notificación al usuario del área privada cuando el usuario asignado emite un mensaje en una conversación.', 'Nuevo mensaje recibido', 'Apreciado/a $contact_name:\r\n\r\nHa recibido un mensaje en el área privada.\r\n\r\nConversación:\r\n$stic_conversations_subject\r\n\r\nMensaje:\r\n$stic_messages_message\r\n\r\nLo puede consultar y responder en el área privada: $portal_address/?internalpage=single_stic_chat&action=detail&id=$stic_conversations_id', '<p>Apreciado/a $contact_name:</p><p>Ha recibido un mensaje en el área privada.</p><p><strong>Conversación:</strong><br>$stic_conversations_subject</p><p><strong>Mensaje:</strong><br>$stic_messages_message</p><p>Lo puede consultar y responder en el área privada: <a href="$portal_address/?internalpage=single_stic_chat&action=detail&id=$stic_conversations_id">$portal_address</a>.</p>', 0, '1', 0, 'notification'),
    -- Candidatura presentada - Notificación - Interlocutor
    ('4f2c7b91-0c3e-4a2b-9b3e-7c4a9b1e9001', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Candidatura presentada (interlocutor)', 'Notificación al interlocutor cuando una candidatura pasa a Presentada.', 'Candidatura presentada: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Apreciado/a $contact_name:\r\n\r\n$stic_job_applications_stic_job_applications_contacts_name ha presentado su candidatura a la oferta $stic_job_applications_stic_job_applications_stic_job_offers_name.\r\n\r\nEnlace a la candidatura: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Apreciado/a $contact_name:</p><p><strong>$stic_job_applications_stic_job_applications_contacts_name</strong> ha presentado su candidatura a la oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id">Enlace a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Candidatura aceptada - Notificación - Interlocutor
    ('4f2c7b91-0c3e-4a2b-9b3e-7c4a9b1e9010', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Candidatura aceptada (interlocutor)', 'Notificación al interlocutor cuando una candidatura pasa a Aceptada.', 'Candidatura aceptada: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Apreciado/a $contact_name:\r\n\r\nLa candidatura de $stic_job_applications_stic_job_applications_contacts_name para la oferta $stic_job_applications_stic_job_applications_stic_job_offers_name ha sido aceptada.\r\n\r\nEnlace a la candidatura: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Apreciado/a $contact_name:</p><p>La candidatura de <strong>$stic_job_applications_stic_job_applications_contacts_name</strong> para la oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> ha sido <strong>aceptada</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id">Enlace a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Candidatura rechazada o cerrada - Notificación - Interlocutor
    ('4f2c7b91-0c3e-4a2b-9b3e-7c4a9b1e9011', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Candidatura rechazada/cerrada (interlocutor)', 'Notificación al interlocutor cuando una candidatura pasa a Rechazada o cerrada.', 'Candidatura rechazada o cerrada: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Apreciado/a $contact_name:\r\n\r\nLa candidatura de $stic_job_applications_stic_job_applications_contacts_name para la oferta $stic_job_applications_stic_job_applications_stic_job_offers_name ha sido rechazada o cerrada.\r\n\r\nEnlace a la candidatura: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Apreciado/a $contact_name:</p><p>La candidatura de <strong>$stic_job_applications_stic_job_applications_contacts_name</strong> para la oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong> ha sido <strong>rechazada o cerrada</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id">Enlace a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Candidatura cancelada - Notificación - Usuario asignado
    ('4f2c7b91-0c3e-4a2b-9b3e-7c4a9b1e9002', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Candidatura cancelada (usuario asignado)', 'Notificación al usuario asignado cuando se cancela una candidatura.', 'Candidatura cancelada: $stic_job_applications_stic_job_applications_stic_job_offers_name', '$stic_job_applications_assigned_user_name:\r\n\r\n$stic_job_applications_stic_job_applications_contacts_name ha cancelado su candidatura para la oferta $stic_job_applications_stic_job_applications_stic_job_offers_name.\r\n\r\nEnlace a la candidatura: $sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id', '<p>$stic_job_applications_assigned_user_name:</p><p><strong>$stic_job_applications_stic_job_applications_contacts_name</strong> ha cancelado su candidatura para la oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong>.</p><p><a href="$sugarurl/index.php?module=stic_Job_Applications&action=DetailView&record=$stic_job_applications_id">Enlace a la candidatura</a>.</p>', 0, '1', 0, 'notification'),
    -- Candidatura cancelada - Notificación - Interlocutor
    ('4f2c7b91-0c3e-4a2b-9b3e-7c4a9b1e9003', NOW(), NOW(), '1', '1', NULL, 'Ejemplo - Candidatura cancelada (interlocutor)', 'Notificación al interlocutor cuando se cancela una candidatura.', 'Candidatura cancelada: $stic_job_applications_stic_job_applications_stic_job_offers_name', 'Apreciado/a $contact_name:\r\n\r\n$stic_job_applications_stic_job_applications_contacts_name ha cancelado su candidatura para la oferta $stic_job_applications_stic_job_applications_stic_job_offers_name.\r\n\r\nEnlace a la candidatura: $portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id', '<p>Apreciado/a $contact_name:</p><p><strong>$stic_job_applications_stic_job_applications_contacts_name</strong> ha cancelado su candidatura para la oferta <strong>$stic_job_applications_stic_job_applications_stic_job_offers_name</strong>.</p><p><a href="$portal_address/?internalpage=single_stic_job_applications&action=detail&id=$stic_job_applications_id">Enlace a la candidatura</a>.</p>', 0, '1', 0, 'notification');

-- Ofertas laborales - Notificación - Nueva oferta (usuario asignado)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('3c0a5f6e-0001-4f8a-9a11-3b1b7c2a0200', 'Ofertas laborales - Notificación - Nueva oferta (usuario asignado)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía notificaciones al usuario asignado al crear una nueva oferta laboral.', 0, '1', 'stic_Job_Offers', 'New_Records', 'Inactive', 'On_Save', 0, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('00000bd1-6280-6302-56a9-69fb0de58e31', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3c0a5f6e-0001-4f8a-9a11-3b1b7c2a0200', 1, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'assigned_user_name', 'Not_Equal_To', 'Field', 'created_by_name');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('3c0a5f6e-0001-4f8a-9a11-3b1b7c2a0201', 'Envío notificación  (usuario asignado)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3c0a5f6e-0001-4f8a-9a11-3b1b7c2a0200', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiM2MwYTVmNmUtMTExMS00ZjhhLTlhMTEtM2IxYjdjMmEwMTAxIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxODoiYXNzaWduZWRfdXNlcl9saW5rIjt9fQ==');

-- Ofertas laborales - Notificación - Fecha de cierre vencida sin estado cerrada (usuario asignado)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('000009c0-3302-dbf2-c1b7-69a850a8b6d5', 'Ofertas laborales - Notificación - Fecha de cierre (usuario asignado)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al usuario asignado cuando la fecha de cierre de una oferta sea el día anterior y no tenga estado Cerrada.', 0, '1', 'stic_Job_Offers', 'All_Records', 'Inactive', 'In_Scheduler', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('000000cd-0341-b540-66b5-69a8502ff15d', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000009c0-3302-dbf2-c1b7-69a850a8b6d5', 3, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'assigned_user_name', 'Not_Equal_To', 'Value', NULL),
('000002a2-0646-1de2-e72c-69a85088e3cf', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000009c0-3302-dbf2-c1b7-69a850a8b6d5', 1, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'applications_end_date', 'Equal_To', 'Date', 'YTo0OntpOjA7czo1OiJ0b2RheSI7aToxO3M6NToibWludXMiO2k6MjtzOjE6IjEiO2k6MztzOjM6ImRheSI7fQ=='),
('000003b5-2bb2-8999-84b6-69a850918ce2', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000009c0-3302-dbf2-c1b7-69a850a8b6d5', 2, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'status', 'Not_Equal_To', 'Multi', '^closed_covered^,^closed_partially_covered^,^closed_not_covered^');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000727-a7fd-96e4-64fa-69a850c229f5', 'Envío notificación (usuario asignado)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000009c0-3302-dbf2-c1b7-69a850a8b6d5', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIwIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiZDNjMWQ1YjctZjhkMi00ZGY0LTlmNmItMmM2M2FhNmI4ZTQxIjtzOjEzOiJvdXRib3VuZF9zbXRwIjtzOjY6InN5c3RlbSI7czoxNToiZnJvbV9lbWFpbF9uYW1lIjtzOjA6IiI7czoxODoiZnJvbV9lbWFpbF9hZGRyZXNzIjtzOjA6IiI7czoxMzoicmVwbHlfdG9fbmFtZSI7czowOiIiO3M6ODoicmVwbHlfdG8iO3M6MDoiIjtzOjEzOiJlbWFpbF90b190eXBlIjthOjE6e2k6MDtzOjI6InRvIjt9czoxNzoiZW1haWxfdGFyZ2V0X3R5cGUiO2E6MTp7aTowO3M6MTM6IlJlbGF0ZWQgRmllbGQiO31zOjU6ImVtYWlsIjthOjE6e2k6MDtzOjE4OiJhc3NpZ25lZF91c2VyX2xpbmsiO319');

-- Ofertas laborales - Notificación - Fecha de cierre vencida sin estado cerrada (interlocutor)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000815-c8ac-f000-0454-69fb1eb45882', 'Ofertas laborales - Notificación - Fecha de cierre (interlocutor)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al interlocutor cuando la fecha de cierre en una oferta sea el día anterior y no tenga de estado Cerrada.', 0, '1', 'stic_Job_Offers', 'All_Records', 'Inactive', 'In_Scheduler', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('000002f1-b9de-d1e8-df06-69fb1eaaa748', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000815-c8ac-f000-0454-69fb1eb45882', 1, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'applications_end_date', 'Equal_To', 'Date', 'YTo0OntpOjA7czo1OiJ0b2RheSI7aToxO3M6NToibWludXMiO2k6MjtzOjE6IjEiO2k6MztzOjM6ImRheSI7fQ=='),
('00000a88-3ede-584f-ae0e-69fb1eed8a19', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000815-c8ac-f000-0454-69fb1eb45882', 3, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'interlocutor', 'Not_Equal_To', 'Value', NULL),
('00000cec-1ccd-0c68-a46d-69fb1e96bc1c', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000815-c8ac-f000-0454-69fb1eb45882', 2, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'status', 'Not_Equal_To', 'Multi', '^closed_covered^,^closed_partially_covered^,^closed_not_covered^');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000338-84ca-31fe-96f1-69fb1e28a9db', 'Envío notificación (interlocutor)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000815-c8ac-f000-0454-69fb1eb45882', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIwIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiYzJhOWU5ZDEtMWY1Zi00YzZjLTliM2MtOGQzYzJhN2Y0YjgxIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxMjoiaW50ZXJsb2N1dG9yIjt9fQ==');

-- Candidaturas - Notificación - Nueva candidatura (usuario asignado / candidato)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a101', 'Candidaturas - Notificación - Nueva candidatura (usuario asignado / candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al usuario asignado cuando una tercera persona (un potencial candidato u otro usuario del CRM) crea una candidatura. El candidato también recibe confirmación.', 0, '1', 'stic_Job_Applications', 'New_Records', 'Inactive', 'On_Save', 0, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('0000043a-c7f6-133c-4b52-69fb5600df06', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a101', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'created_by_name', 'Not_Equal_To', 'Field', 'assigned_user_name'),
('0000047a-f4b7-3937-dff0-69d8c03ca9bd', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a101', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'review');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a103', 'Envío notificación (usuario asignado)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a101', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiN2E5ZjhmM2EtMmQxZi00YTQwLTlkZDYtN2M2ZjllMWI3MDAxIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxODoiYXNzaWduZWRfdXNlcl9saW5rIjt9fQ=='),
('2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a104', 'Envío notificación (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a101', 2, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiN2E5ZjhmM2EtMmQxZi00YTQwLTlkZDYtN2M2ZjllMWI3MDAzIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MzA6InN0aWNfam9iX2FwcGxpY2F0aW9uc19jb250YWN0cyI7fX0=');

-- Candidaturas - Notificación - Nueva candidatura (candidato)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('000006a9-afb9-d96f-0c92-69fb56113842', 'Candidaturas - Notificación - Nueva candidatura (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al candidato el usuario asignado crea una candidatura en su nombre.', 0, '1', 'stic_Job_Applications', 'New_Records', 'Inactive', 'On_Save', 0, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('0000074b-8f66-a4cf-721f-69fb56d5b469', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000006a9-afb9-d96f-0c92-69fb56113842', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'created_by_name', 'Equal_To', 'Field', 'assigned_user_name'),
('0000095f-fb16-acd0-9a04-69fb56f0038e', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000006a9-afb9-d96f-0c92-69fb56113842', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'review');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000958-87e6-f511-43f9-69fb56e5893a', 'Envío notificación (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000006a9-afb9-d96f-0c92-69fb56113842', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiN2E5ZjhmM2EtMmQxZi00YTQwLTlkZDYtN2M2ZjllMWI3MDAzIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czozMDoic3RpY19qb2JfYXBwbGljYXRpb25zX2NvbnRhY3RzIjt9fQ==');

-- Candidaturas - Notificación - Presentada (candidato)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000f20-7b3a-4a1b-8f2a-69a830ec33d0', 'Candidaturas - Notificación - Presentada (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al candidato cuando una candidatura pasa a estado Presentada.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('00000f21-7b3a-4a1b-8f2a-69a830ec33d0', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000f20-7b3a-4a1b-8f2a-69a830ec33d0', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'presented'),
('00000f22-7b3a-4a1b-8f2a-69a830ec33d0', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000f20-7b3a-4a1b-8f2a-69a830ec33d0', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL);
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000f23-7b3a-4a1b-8f2a-69a830ec33d0', 'Envío notificación (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000f20-7b3a-4a1b-8f2a-69a830ec33d0', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA4IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MzA6InN0aWNfam9iX2FwcGxpY2F0aW9uc19jb250YWN0cyI7fX0=');

-- Candidaturas - Notificación - Aceptada (usuario asignado / candidato)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000190-75e4-3e38-5f8f-69a82fb83c15', 'Candidaturas - Notificación - Aceptada (usuario asignado / candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al usuario asignado y al candidato cuando un tercero (el interlocutor externo u otro usuario del CRM) cambia una candidatura a Aceptada.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('000003b6-1b3f-4bc3-b4f5-69a82f8345f3', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000190-75e4-3e38-5f8f-69a82fb83c15', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'accepted'),
('00000778-cf26-a3ea-ab3c-69fb592f7d71', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000190-75e4-3e38-5f8f-69a82fb83c15', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Not_Equal_To', 'Field', 'assigned_user_name'),
('00000f10-1111-2222-3333-69a82fb83c15', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000190-75e4-3e38-5f8f-69a82fb83c15', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL);
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('000009bf-d247-6e61-ac71-69a82f5103df', 'Envío notificación (usuario asignado)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000190-75e4-3e38-5f8f-69a82fb83c15', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDAxIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MTg6ImFzc2lnbmVkX3VzZXJfbGluayI7fX0='),
('000009c1-d247-6e61-ac71-69a82f5103d1', 'Envío notificación (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000190-75e4-3e38-5f8f-69a82fb83c15', 2, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDAyIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MzA6InN0aWNfam9iX2FwcGxpY2F0aW9uc19jb250YWN0cyI7fX0=');

-- Candidaturas - Notificación - Aceptada (candidato)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000101-4d1c-b7e4-7fc4-69fb5af86cfa', 'Candidaturas - Notificación - Aceptada (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al candidato cuando el usuario asignado cambia una candidatura a Aceptada.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('0000054f-feaa-42b0-ba34-69fb5a7a4d76', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000101-4d1c-b7e4-7fc4-69fb5af86cfa', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Equal_To', 'Field', 'assigned_user_name'),
('00000876-3720-e155-6d3a-69fb5aaf478a', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000101-4d1c-b7e4-7fc4-69fb5af86cfa', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL),
('00000b3c-676c-7b20-3da5-69fb5abe6397', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000101-4d1c-b7e4-7fc4-69fb5af86cfa', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'accepted');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('000007cf-9d70-dd55-61c1-69fb5adc6f5b', 'Envío notificación (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000101-4d1c-b7e4-7fc4-69fb5af86cfa', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDAyIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czozMDoic3RpY19qb2JfYXBwbGljYXRpb25zX2NvbnRhY3RzIjt9fQ==');

-- Candidaturas - Notificación - Estado Rechazada o cerrada (usuario asignado / candidato)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000ace-02d2-2425-107e-69a82a9eacb5', 'Candidaturas - Notificación - Estado Rechazada o cerrada (usuario asignado / candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al candidato y al usuario asignado cuando un tercero (el interlocutor externo u otro usuario del CRM) cambia la candidatura a Rechazada o cerrada.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('000001a5-41d3-7d65-fe58-69a82a22be9d', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'rejected_closed'),
('00000bb2-129d-3cff-4d79-69fb5a5c974d', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 4, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Not_Equal_To', 'Field', 'assigned_user_name'),
('00000f11-1111-2222-3333-69a82a9eacb5', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL),
('00000f14-7b3a-4a1b-8f2a-69a82a9eacb6', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'rejection_reason', 'Not_Equal_To', 'Value', 'resignation');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000b52-cd9a-161e-c7d1-69a82a27d7fb', 'Envío notificación (usuario asignado)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA0IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MTg6ImFzc2lnbmVkX3VzZXJfbGluayI7fX0='),
('00000b53-cd9a-161e-c7d1-69a82a27d7f1', 'Envío notificación (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 2, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA1IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MzA6InN0aWNfam9iX2FwcGxpY2F0aW9uc19jb250YWN0cyI7fX0=');

-- Candidaturas - Notificación - Estado Rechazada o cerrada (candidato)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('000001be-e27b-e9a6-98aa-69fb5a33138a', 'Candidaturas - Notificación - Estado Rechazada o cerrada (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al candidato cuando el usuario asignado cambia una candidatura a Rechazada o cerrada.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('00000181-a6bf-cbe4-a82a-69fb5ae259c6', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000001be-e27b-e9a6-98aa-69fb5a33138a', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL),
('00000214-51dc-4a76-e116-69fb5a064799', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000001be-e27b-e9a6-98aa-69fb5a33138a', 4, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Equal_To', 'Field', 'assigned_user_name'),
('00000849-bf4b-beca-85d7-69fb5a80dc0e', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000001be-e27b-e9a6-98aa-69fb5a33138a', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'rejection_reason', 'Not_Equal_To', 'Value', 'resignation'),
('000009d7-2129-6ea1-ff80-69fb5acbdca7', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000001be-e27b-e9a6-98aa-69fb5a33138a', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'rejected_closed');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('0000085b-5ed1-39bc-6fc1-69fb5a995e7a', 'Envío notificación (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000001be-e27b-e9a6-98aa-69fb5a33138a', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA1IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czozMDoic3RpY19qb2JfYXBwbGljYXRpb25zX2NvbnRhY3RzIjt9fQ==');

-- Candidaturas - Notificación - Otros estados (usuario asignado / candidato)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000174-497a-ef41-5ae8-69a830ec33ce', 'Candidaturas - Notificación - Otros estados (usuario asignado / candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al candidato y al usuario asignado cuando un tercero (el interlocutor externo u otro usuario del CRM) cambia una candidatura a los estados Pendiente entrevista o Entrevistada.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('0000033d-8ae0-fe4a-64ba-69a830439caf', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000174-497a-ef41-5ae8-69a830ec33ce', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Multi', '^pending_interview^,^interviewed^'),
('00000603-e27d-aab5-227a-69fb24be4977', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000174-497a-ef41-5ae8-69a830ec33ce', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Not_Equal_To', 'Field', 'assigned_user_name'),
('00000f12-1111-2222-3333-69a830ec33ce', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000174-497a-ef41-5ae8-69a830ec33ce', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL);
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000b79-f2fc-034b-4bb2-69a830fb223b', 'Envío notificación (usuario asignado)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000174-497a-ef41-5ae8-69a830ec33ce', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA3IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxODoiYXNzaWduZWRfdXNlcl9saW5rIjt9fQ=='),
('00000b80-f2fc-034b-4bb2-69a830fb2240', 'Envío notificación (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000174-497a-ef41-5ae8-69a830ec33ce', 2, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA4IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czozMDoic3RpY19qb2JfYXBwbGljYXRpb25zX2NvbnRhY3RzIjt9fQ==');

-- Ofertas laborales - Notificación - Nueva oferta (usuario asignado)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('3c0a5f6e-0001-4f8a-9a11-3b1b7c2a0200', 'Ofertas laborales - Notificación - Nueva oferta (usuario asignado)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía notificaciones al usuario asignado al crear una nueva oferta laboral.', 0, '1', 'stic_Job_Offers', 'New_Records', 'Inactive', 'On_Save', 0, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('00000bd1-6280-6302-56a9-69fb0de58e31', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3c0a5f6e-0001-4f8a-9a11-3b1b7c2a0200', 1, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'assigned_user_name', 'Not_Equal_To', 'Field', 'created_by_name');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('3c0a5f6e-0001-4f8a-9a11-3b1b7c2a0201', 'Envío notificación  (usuario asignado)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3c0a5f6e-0001-4f8a-9a11-3b1b7c2a0200', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiM2MwYTVmNmUtMTExMS00ZjhhLTlhMTEtM2IxYjdjMmEwMTAxIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxODoiYXNzaWduZWRfdXNlcl9saW5rIjt9fQ==');

-- Ofertas laborales - Notificación - Fecha de cierre vencida sin estado cerrada (usuario asignado)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('000009c0-3302-dbf2-c1b7-69a850a8b6d5', 'Ofertas laborales - Notificación - Fecha de cierre (usuario asignado)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al usuario asignado cuando la fecha de cierre de una oferta sea el día anterior y no tenga estado Cerrada.', 0, '1', 'stic_Job_Offers', 'All_Records', 'Inactive', 'In_Scheduler', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('000000cd-0341-b540-66b5-69a8502ff15d', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000009c0-3302-dbf2-c1b7-69a850a8b6d5', 3, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'assigned_user_name', 'Not_Equal_To', 'Value', NULL),
('000002a2-0646-1de2-e72c-69a85088e3cf', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000009c0-3302-dbf2-c1b7-69a850a8b6d5', 1, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'applications_end_date', 'Equal_To', 'Date', 'YTo0OntpOjA7czo1OiJ0b2RheSI7aToxO3M6NToibWludXMiO2k6MjtzOjE6IjEiO2k6MztzOjM6ImRheSI7fQ=='),
('000003b5-2bb2-8999-84b6-69a850918ce2', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000009c0-3302-dbf2-c1b7-69a850a8b6d5', 2, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'status', 'Not_Equal_To', 'Multi', '^closed_covered^,^closed_partially_covered^,^closed_not_covered^');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000727-a7fd-96e4-64fa-69a850c229f5', 'Envío notificación (usuario asignado)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000009c0-3302-dbf2-c1b7-69a850a8b6d5', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIwIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiZDNjMWQ1YjctZjhkMi00ZGY0LTlmNmItMmM2M2FhNmI4ZTQxIjtzOjEzOiJvdXRib3VuZF9zbXRwIjtzOjY6InN5c3RlbSI7czoxNToiZnJvbV9lbWFpbF9uYW1lIjtzOjA6IiI7czoxODoiZnJvbV9lbWFpbF9hZGRyZXNzIjtzOjA6IiI7czoxMzoicmVwbHlfdG9fbmFtZSI7czowOiIiO3M6ODoicmVwbHlfdG8iO3M6MDoiIjtzOjEzOiJlbWFpbF90b190eXBlIjthOjE6e2k6MDtzOjI6InRvIjt9czoxNzoiZW1haWxfdGFyZ2V0X3R5cGUiO2E6MTp7aTowO3M6MTM6IlJlbGF0ZWQgRmllbGQiO31zOjU6ImVtYWlsIjthOjE6e2k6MDtzOjE4OiJhc3NpZ25lZF91c2VyX2xpbmsiO319');

-- Ofertas laborales - Notificación - Fecha de cierre vencida sin estado cerrada (interlocutor)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000815-c8ac-f000-0454-69fb1eb45882', 'Ofertas laborales - Notificación - Fecha de cierre (interlocutor)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al interlocutor cuando la fecha de cierre en una oferta sea el día anterior y no tenga de estado Cerrada.', 0, '1', 'stic_Job_Offers', 'All_Records', 'Inactive', 'In_Scheduler', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('000002f1-b9de-d1e8-df06-69fb1eaaa748', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000815-c8ac-f000-0454-69fb1eb45882', 1, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'applications_end_date', 'Equal_To', 'Date', 'YTo0OntpOjA7czo1OiJ0b2RheSI7aToxO3M6NToibWludXMiO2k6MjtzOjE6IjEiO2k6MztzOjM6ImRheSI7fQ=='),
('00000a88-3ede-584f-ae0e-69fb1eed8a19', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000815-c8ac-f000-0454-69fb1eb45882', 3, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'interlocutor', 'Not_Equal_To', 'Value', NULL),
('00000cec-1ccd-0c68-a46d-69fb1e96bc1c', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000815-c8ac-f000-0454-69fb1eb45882', 2, 'YToxOntpOjA7czoxNToic3RpY19Kb2JfT2ZmZXJzIjt9', 'status', 'Not_Equal_To', 'Multi', '^closed_covered^,^closed_partially_covered^,^closed_not_covered^');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000338-84ca-31fe-96f1-69fb1e28a9db', 'Envío notificación (interlocutor)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000815-c8ac-f000-0454-69fb1eb45882', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIwIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiYzJhOWU5ZDEtMWY1Zi00YzZjLTliM2MtOGQzYzJhN2Y0YjgxIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxMjoiaW50ZXJsb2N1dG9yIjt9fQ==');

-- Candidaturas - Notificación - Nueva candidatura (usuario asignado / candidato)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a101', 'Candidaturas - Notificación - Nueva candidatura (usuario asignado / candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al usuario asignado cuando una tercera persona (un potencial candidato u otro usuario del CRM) crea una candidatura. El candidato también recibe confirmación.', 0, '1', 'stic_Job_Applications', 'New_Records', 'Inactive', 'On_Save', 0, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('0000043a-c7f6-133c-4b52-69fb5600df06', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a101', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'created_by_name', 'Not_Equal_To', 'Field', 'assigned_user_name'),
('0000047a-f4b7-3937-dff0-69d8c03ca9bd', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a101', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'review');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a103', 'Envío notificación (usuario asignado)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a101', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiN2E5ZjhmM2EtMmQxZi00YTQwLTlkZDYtN2M2ZjllMWI3MDAxIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxODoiYXNzaWduZWRfdXNlcl9saW5rIjt9fQ=='),
('2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a104', 'Envío notificación (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '2f1b6d2e-6b9c-4b06-9c1e-4b3d4d80a101', 2, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiN2E5ZjhmM2EtMmQxZi00YTQwLTlkZDYtN2M2ZjllMWI3MDAzIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MzA6InN0aWNfam9iX2FwcGxpY2F0aW9uc19jb250YWN0cyI7fX0=');

-- Candidaturas - Notificación - Nueva candidatura (candidato)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('000006a9-afb9-d96f-0c92-69fb56113842', 'Candidaturas - Notificación - Nueva candidatura (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al candidato el usuario asignado crea una candidatura en su nombre.', 0, '1', 'stic_Job_Applications', 'New_Records', 'Inactive', 'On_Save', 0, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('0000074b-8f66-a4cf-721f-69fb56d5b469', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000006a9-afb9-d96f-0c92-69fb56113842', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'created_by_name', 'Equal_To', 'Field', 'assigned_user_name'),
('0000095f-fb16-acd0-9a04-69fb56f0038e', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000006a9-afb9-d96f-0c92-69fb56113842', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'review');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000958-87e6-f511-43f9-69fb56e5893a', 'Envío notificación (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000006a9-afb9-d96f-0c92-69fb56113842', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiN2E5ZjhmM2EtMmQxZi00YTQwLTlkZDYtN2M2ZjllMWI3MDAzIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czozMDoic3RpY19qb2JfYXBwbGljYXRpb25zX2NvbnRhY3RzIjt9fQ==');

-- Candidaturas - Notificación - Presentada (candidato)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000f20-7b3a-4a1b-8f2a-69a830ec33d0', 'Candidaturas - Notificación - Presentada (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al candidato cuando una candidatura pasa a estado Presentada.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('00000f21-7b3a-4a1b-8f2a-69a830ec33d0', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000f20-7b3a-4a1b-8f2a-69a830ec33d0', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'presented'),
('00000f22-7b3a-4a1b-8f2a-69a830ec33d0', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000f20-7b3a-4a1b-8f2a-69a830ec33d0', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL);
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000f23-7b3a-4a1b-8f2a-69a830ec33d0', 'Envío notificación (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000f20-7b3a-4a1b-8f2a-69a830ec33d0', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA4IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MzA6InN0aWNfam9iX2FwcGxpY2F0aW9uc19jb250YWN0cyI7fX0=');

-- Candidaturas - Notificación - Aceptada (usuario asignado / candidato)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000190-75e4-3e38-5f8f-69a82fb83c15', 'Candidaturas - Notificación - Aceptada (usuario asignado / candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al usuario asignado y al candidato cuando un tercero (el interlocutor externo u otro usuario del CRM) cambia una candidatura a Aceptada.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('000003b6-1b3f-4bc3-b4f5-69a82f8345f3', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000190-75e4-3e38-5f8f-69a82fb83c15', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'accepted'),
('00000778-cf26-a3ea-ab3c-69fb592f7d71', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000190-75e4-3e38-5f8f-69a82fb83c15', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Not_Equal_To', 'Field', 'assigned_user_name'),
('00000f10-1111-2222-3333-69a82fb83c15', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000190-75e4-3e38-5f8f-69a82fb83c15', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL);
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('000009bf-d247-6e61-ac71-69a82f5103df', 'Envío notificación (usuario asignado)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000190-75e4-3e38-5f8f-69a82fb83c15', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDAxIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MTg6ImFzc2lnbmVkX3VzZXJfbGluayI7fX0='),
('000009c1-d247-6e61-ac71-69a82f5103d1', 'Envío notificación (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000190-75e4-3e38-5f8f-69a82fb83c15', 2, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDAyIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MzA6InN0aWNfam9iX2FwcGxpY2F0aW9uc19jb250YWN0cyI7fX0=');

-- Candidaturas - Notificación - Aceptada (candidato)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000101-4d1c-b7e4-7fc4-69fb5af86cfa', 'Candidaturas - Notificación - Aceptada (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al candidato cuando el usuario asignado cambia una candidatura a Aceptada.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('0000054f-feaa-42b0-ba34-69fb5a7a4d76', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000101-4d1c-b7e4-7fc4-69fb5af86cfa', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Equal_To', 'Field', 'assigned_user_name'),
('00000876-3720-e155-6d3a-69fb5aaf478a', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000101-4d1c-b7e4-7fc4-69fb5af86cfa', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL),
('00000b3c-676c-7b20-3da5-69fb5abe6397', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000101-4d1c-b7e4-7fc4-69fb5af86cfa', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'accepted');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('000007cf-9d70-dd55-61c1-69fb5adc6f5b', 'Envío notificación (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000101-4d1c-b7e4-7fc4-69fb5af86cfa', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDAyIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czozMDoic3RpY19qb2JfYXBwbGljYXRpb25zX2NvbnRhY3RzIjt9fQ==');

-- Candidaturas - Notificación - Estado Rechazada o cerrada (usuario asignado / candidato)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000ace-02d2-2425-107e-69a82a9eacb5', 'Candidaturas - Notificación - Estado Rechazada o cerrada (usuario asignado / candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al candidato y al usuario asignado cuando un tercero (el interlocutor externo u otro usuario del CRM) cambia la candidatura a Rechazada o cerrada.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('000001a5-41d3-7d65-fe58-69a82a22be9d', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'rejected_closed'),
('00000bb2-129d-3cff-4d79-69fb5a5c974d', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 4, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Not_Equal_To', 'Field', 'assigned_user_name'),
('00000f11-1111-2222-3333-69a82a9eacb5', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL),
('00000f14-7b3a-4a1b-8f2a-69a82a9eacb6', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'rejection_reason', 'Not_Equal_To', 'Value', 'resignation');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000b52-cd9a-161e-c7d1-69a82a27d7fb', 'Envío notificación (usuario asignado)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA0IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MTg6ImFzc2lnbmVkX3VzZXJfbGluayI7fX0='),
('00000b53-cd9a-161e-c7d1-69a82a27d7f1', 'Envío notificación (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000ace-02d2-2425-107e-69a82a9eacb5', 2, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA1IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToyOntpOjA7czoyOiJ0byI7aToxO3M6MjoiY2MiO31zOjE3OiJlbWFpbF90YXJnZXRfdHlwZSI7YToxOntpOjA7czoxMzoiUmVsYXRlZCBGaWVsZCI7fXM6NToiZW1haWwiO2E6MTp7aTowO3M6MzA6InN0aWNfam9iX2FwcGxpY2F0aW9uc19jb250YWN0cyI7fX0=');

-- Candidaturas - Notificación - Estado Rechazada o cerrada (candidato)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('000001be-e27b-e9a6-98aa-69fb5a33138a', 'Candidaturas - Notificación - Estado Rechazada o cerrada (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al candidato cuando el usuario asignado cambia una candidatura a Rechazada o cerrada.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('00000181-a6bf-cbe4-a82a-69fb5ae259c6', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000001be-e27b-e9a6-98aa-69fb5a33138a', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL),
('00000214-51dc-4a76-e116-69fb5a064799', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000001be-e27b-e9a6-98aa-69fb5a33138a', 4, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Equal_To', 'Field', 'assigned_user_name'),
('00000849-bf4b-beca-85d7-69fb5a80dc0e', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000001be-e27b-e9a6-98aa-69fb5a33138a', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'rejection_reason', 'Not_Equal_To', 'Value', 'resignation'),
('000009d7-2129-6ea1-ff80-69fb5acbdca7', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000001be-e27b-e9a6-98aa-69fb5a33138a', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Value', 'rejected_closed');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('0000085b-5ed1-39bc-6fc1-69fb5a995e7a', 'Envío notificación (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000001be-e27b-e9a6-98aa-69fb5a33138a', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA1IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czozMDoic3RpY19qb2JfYXBwbGljYXRpb25zX2NvbnRhY3RzIjt9fQ==');

-- Candidaturas - Notificación - Otros estados (usuario asignado / candidato)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('00000174-497a-ef41-5ae8-69a830ec33ce', 'Candidaturas - Notificación - Otros estados (usuario asignado / candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al candidato y al usuario asignado cuando un tercero (el interlocutor externo u otro usuario del CRM) cambia una candidatura a los estados Pendiente entrevista o Entrevistada.', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('0000033d-8ae0-fe4a-64ba-69a830439caf', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000174-497a-ef41-5ae8-69a830ec33ce', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Multi', '^pending_interview^,^interviewed^'),
('00000603-e27d-aab5-227a-69fb24be4977', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000174-497a-ef41-5ae8-69a830ec33ce', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Not_Equal_To', 'Field', 'assigned_user_name'),
('00000f12-1111-2222-3333-69a830ec33ce', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000174-497a-ef41-5ae8-69a830ec33ce', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL);
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000b79-f2fc-034b-4bb2-69a830fb223b', 'Envío notificación (usuario asignado)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000174-497a-ef41-5ae8-69a830ec33ce', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA3IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxODoiYXNzaWduZWRfdXNlcl9saW5rIjt9fQ=='),
('00000b80-f2fc-034b-4bb2-69a830fb2240', 'Envío notificación (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '00000174-497a-ef41-5ae8-69a830ec33ce', 2, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA4IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czozMDoic3RpY19qb2JfYXBwbGljYXRpb25zX2NvbnRhY3RzIjt9fQ==');

-- Candidaturas - Notificación - Otros estados (candidato)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('000003e0-ebe2-ff1f-40d2-69fb278f5ab6', 'Candidaturas - Notificación - Otros estados (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al candidato cuando el usuario asignado cambia el estado de una candidatura a los estados Pendiente entrevista o Entrevistada', 0, '1', 'stic_Job_Applications', 'Modified_Records', 'Inactive', 'On_Save', 1, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('00000026-e7ad-3c88-57b0-69fb27298480', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000003e0-ebe2-ff1f-40d2-69fb278f5ab6', 3, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'modified_by_name', 'Equal_To', 'Field', 'assigned_user_name'),
('0000019e-3313-a824-8459-69fb275e68a5', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000003e0-ebe2-ff1f-40d2-69fb278f5ab6', 2, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Any_Change', NULL),
('00000bcb-699f-9731-d947-69fb27e8ef59', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000003e0-ebe2-ff1f-40d2-69fb278f5ab6', 1, 'YToxOntpOjA7czoyMToic3RpY19Kb2JfQXBwbGljYXRpb25zIjt9', 'status', 'Equal_To', 'Multi', '^pending_interview^,^interviewed^');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('00000225-589a-fac8-0b73-69fb275b376d', 'Envío notificación (candidato)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '000003e0-ebe2-ff1f-40d2-69fb278f5ab6', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiMWEyZDZmMTAtOGUzMi00ZjhhLTlhMTEtM2IxYjdjMmEwMDA4IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czozMDoic3RpY19qb2JfYXBwbGljYXRpb25zX2NvbnRhY3RzIjt9fQ==');

-- Mensajes - Notificación - Nuevo mensaje (usuario asignado)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b201', 'Mensajes - Notificación - Nuevo mensaje (usuario asignado)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al usuario asignado cuando un usuario del área privada (interlocutor o candidato) emite un mensaje en una conversación.', 0, '1', 'stic_Messages', 'New_Records', 'Inactive', 'On_Save', 0, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b202', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b201', 1, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'type', 'Equal_To', 'Value', 'private_area'),
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b203', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b201', 2, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'status', 'Equal_To', 'Value', 'sent'),
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b204', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b201', 3, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'parent_type', 'Equal_To', 'Value', 'Contacts');
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b206', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b201', 4, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'direction', 'Equal_To', 'Value', 'inbound');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b205', 'Envío notificación (usuario asignado)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b201', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiN2E5ZjhmM2EtMmQxZi00YTQwLTlkZDYtN2M2ZjllMWI3MDAyIjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxODoiYXNzaWduZWRfdXNlcl9saW5rIjt9fQ==');

-- Mensajes - Notificación - Nuevo mensaje (usuario del área privada)
REPLACE INTO aow_workflow (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, flow_module, flow_run_on, status, run_when, multiple_runs, run_on_import) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b210', 'Mensajes - Notificación - Nuevo mensaje (usuario del área privada)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', 'Flujo de trabajo que envía una notificación al usuario del área privada (interlocutor o candidato) cuando el usuario asignado emite un mensaje en una conversación.', 0, '1', 'stic_Messages', 'New_Records', 'Inactive', 'On_Save', 0, 0);
REPLACE INTO aow_conditions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, condition_order, module_path, field, operator, value_type, value) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b212', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b210', 1, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'type', 'Equal_To', 'Value', 'private_area'),
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b213', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b210', 2, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'status', 'Equal_To', 'Value', 'sent'),
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b214', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b210', 3, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'parent_type', 'Equal_To', 'Value', 'Contacts'),
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b215', '', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b210', 4, 'YToxOntpOjA7czoxMzoic3RpY19NZXNzYWdlcyI7fQ==', 'direction', 'Equal_To', 'Value', 'outbound');
REPLACE INTO aow_actions (id, name, date_entered, date_modified, modified_user_id, created_by, description, deleted, aow_workflow_id, action_order, action, parameters) VALUES
('3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b211', 'Envío notificación (usuario del área privada)', UTC_TIMESTAMP(), UTC_TIMESTAMP(), '1', '1', NULL, 0, '3a5c7d8e-8b2f-4c1c-9c2b-6e6b0c90b210', 1, 'SendEmail', 'YToxMDp7czoxNjoiaW5kaXZpZHVhbF9lbWFpbCI7czoxOiIxIjtzOjE0OiJlbWFpbF90ZW1wbGF0ZSI7czozNjoiN2E5ZjhmM2EtMmQxZi00YTQwLTlkZDYtN2M2ZjllMWI3MDA0IjtzOjExOiJvdXRwdXRfc210cCI7czo2OiJzeXN0ZW0iO3M6MTU6ImZyb21fZW1haWxfbmFtZSI7czowOiIiO3M6MTg6ImZyb21fZW1haWxfYWRkcmVzcyI7czowOiIiO3M6MTM6InJlcGx5X3RvX25hbWUiO3M6MDoiIjtzOjg6InJlcGx5X3RvIjtzOjA6IiI7czoxMzoiZW1haWxfdG9fdHlwZSI7YToxOntpOjA7czoyOiJ0byI7fXM6MTc6ImVtYWlsX3RhcmdldF90eXBlIjthOjE6e2k6MDtzOjEzOiJSZWxhdGVkIEZpZWxkIjt9czo1OiJlbWFpbCI7YToxOntpOjA7czoxOToicGFyZW50X2NvbnRhY3RfbmFtZSI7fX0=');

-- Configuración para el envío de credenciales del Área Privada
REPLACE INTO `stic_settings` (`id`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `deleted`, `assigned_user_id`, `type`, `name`, `value`, `description`) VALUES
('f8b4a3a2-9f40-4c2e-9f8d-5e76a20f5d11', NOW(), NOW(), '1', '1', 0, '1', 'PRIVATEAREA', 'PRIVATEAREA_SEND_CREDENTIALS_ON_ENABLE', '0', 'Indica si se enviarán automáticamente las credenciales del Área Privada al marcar el campo "Activar Área Privada" de los módulos Personas y Organizaciones (0 = No (valor por defecto), 1 = Sí).'),
('4ef9497d-6511-4a87-9467-01ca8ac99f20', NOW(), NOW(), '1', '1', 0, '1', 'PRIVATEAREA', 'PRIVATEAREA_CREDENTIALS_TEMPLATE_CONTACTS', '6e6f5a91-2cb9-4f42-bf26-0a13b2f1c101', 'ID de la plantilla de correo de tipo Notificación para el envío de credenciales del Área Privada en Personas'),
('8a2014ed-569d-44ad-b03a-f39420aa7ef6', NOW(), NOW(), '1', '1', 0, '1', 'PRIVATEAREA', 'PRIVATEAREA_CREDENTIALS_TEMPLATE_ACCOUNTS', '6e6f5a91-2cb9-4f42-bf26-0a13b2f1c102', 'ID de la plantilla de correo de tipo Notificación para el envío de credenciales del Área Privada en Organizaciones');
